### ISSUE TITLE
Website took lot of time to render/load it's content

### ISSUE THREAD

**Issue by pankaj-2503** [Submitty/Submitty#10099]
**What problem are you trying to solve with Submitty**

While navigating on Submittly main website the links took too time to load it's content , there might be some problems in backend/server.
**Describe the way you'd like to solve this problem**

![image](https://github.com/Submitty/Submitty/assets/90036864/77706bb5-2124-4c35-a05d-37b29ab8a776)

**Describe any potential alternatives you'd tried to solve the problem**

**Additional context**

**Comment by williamjallen** [comment]
I just confirmed that the issue affects [this](https://submitty.org/instructor/course_settings/rainbow_grades/index) documentation site.  The issue is that the image in your screenshot is 4 MB.

@ziesski (or someone else familiar with rainbow grades), can you please submit a PR to change this to a lower resolution image?
