### ISSUE TITLE
Change gradable version while waiting on queue for grading.  

### ISSUE THREAD

**Issue by Aeonoi** [Submitty/Submitty#10366]
Recently, one of the classes had a homework that required a lot of time/resources from Submitty which required students to wait in a long queue and might not get it graded before the submission deadline. A student might want to change which submission they want to be graded while also waiting on a submission to be graded. However, if you were to switch which version to be graded, it may kick you out of the queue.

**Comment by bmcutler** [comment]
This is not a detailed description of an actual bug.  This is normal functioning of the autograding queue on a busy night.  Students are allowed to make multiple submissions.  Assignments are graded in the order received on available hardware.  Assignments in different courses have different resource requirements and may grade more quickly relative to each other because they are running on different physical servers.
