### ISSUE TITLE
Duplicate Email Notification

### ISSUE THREAD

**Issue by williamschen23** [Submitty/Submitty#10462]
**Describe the bug**
Recently as summer classes started, two emails have been sent out for every notification. This was consistent across different classes, ie. CSCI-4210 and RCOS. 

**Expected behavior**
There should only be one email sent per notification that the user has selected.

**To Reproduce**
From what I can tell in the Submitty VM under email status, one notification should be sent out, so this is most likely a race condition issue with submitty_daemon. I have not been able to configure emails properly.
1. Configure emails on VM.
2. Send out an email.
3. Check for duplicate sent email.

**Screenshots**

<img width="834" alt="image" src="https://github.com/Submitty/Submitty/assets/82904790/ec71fd1a-45ea-4dbd-962a-1c4c78b30add">
<img width="838" alt="image" src="https://github.com/Submitty/Submitty/assets/82904790/79f2fb58-c003-4b17-ab08-25b7a2b91f4d">
<img width="368" alt="image" src="https://github.com/Submitty/Submitty/assets/82904790/458b6601-e958-4395-bf36-f86fc6692d2f">
<br>
Same contents

**Comment by bmcutler** [comment]
This happened because we had 2 webserver VMs (the real one, and a backup server we use for testing) connected to the same database VM.  This is specified in /usr/local/submitty/config/database.json.  The backup webserver VM should have instead been connected to the backup database VM.   Situation was resolved when change was made.

NOTE: Without adding more configuration complexity, there isn't a simple way to detect/prevent this in the future.
