### ISSUE TITLE
Posts can go past post box width

### ISSUE THREAD

**Issue by micpap25** [Submitty/Submitty#10485]
**Describe the bug**
When posting to a forum, a sufficiently long word can go past the width of the post box area.

**Expected behavior**
You should be able to scroll the post horizontally if it is possible to scroll it.

**To Reproduce**
1. Make a post.
2. Type a very long word (no spaces) on a single line.

**Configuration**
 - OS: Windows
 - Browser: Chrome

**Screenshots**
![image](https://github.com/Submitty/Submitty/assets/34077605/8b37a0ff-3f6c-4a67-b6ca-78201ba7442e)

**Comment by powe97** [comment]
Code blocks also overflow off the right side of the screen, and there is no way to scroll to the right. Instead of wrapping lines of text in code blocks, we should have some way to scroll a code block when the block is very wide.

![image](https://github.com/Submitty/Submitty/assets/116031952/7bb74506-d04a-465d-a8e9-fafe107ba67c)

**Comment by micpap25** [comment]
This might cause the category not to display / the thread list to look odd as well 
![image](https://github.com/Submitty/Submitty/assets/34077605/40ebad80-99e4-446a-8b7c-b47d876d60ca)

**Comment by ZheyuDeng** [comment]
Is this what you expected it to looks like?
![image](https://github.com/Submitty/Submitty/assets/122962727/bdaf4647-cf01-4924-8bb1-d13740b9a2ca)
