### ISSUE TITLE
When downloading a student's code as a ZIP file, their RCSID is exposed

### ISSUE THREAD

**Issue by ION606** [Submitty/Submitty#10601]
**Describe the bug**

When downloading a student's code as a ZIP file, I'm pretty sure their RCSID is exposed.

**Expected behavior**

Some sort of anonymous file name

**To Reproduce**
1. go to any grading portal
2. select "download zip file"
3. the file name will be `assignementName_RCSID_version`

**Configuration**
 - OS: Fedora Spin Sway
 - Browser Librewolf

**Screenshots**

I would rather not, as I don't want to expose any student's RCSID and I'm not part of the class (just a mentor)

**Additional context**

**Comment by bmcutler** [comment]
To clarify:
If an assignment is configured to be graded by limited access graders, with double-blind grading, then the graders should never see the student user_ids.  Instead, we should be using the anonymous id (which is different/unique for each student for each assignment within the course).  This bug is probably only with the download zip option -- and we should make sure to use the anonymous id for both download a zip of a single student, and also download all of the files for all of the students assigned to the grader.  And it should also be tested for team assignments and VCS assignments as well.
