### ISSUE TITLE
Add memcached to Submitty

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#1081]
We use quite a bit of things all the time that don't necessarily change all that often (course details, gradeable metadata, etc.) day to day. We can employ memcache so that these constructs reside in-memory which means that we don't have to hit our DB/file system to get this data on each page-load, but just have them in cache which should provide some efficiency improvements.

Initially, we'll just cache the course details, and then move more things to the cache as it makes sense.

**Comment by MasterOdin** [comment]
Testing this, I made the following test script:
```
<?php
$time_start = microtime(true);
$x = 100000;
$memcached = true;

echo "starting test...\n\n";

for ($i = 0; $i < $x; $i++) {
    if ($memcached) {
        $mem = new Memcached();
        $mem->addServer('localhost', '11211');

        $json = $mem->get('testjson');
        if ($json === false) {
            $json = json_decode(file_get_contents('test.json'), true);
            $mem->set('testjson', $json, 60*60);
        }
    }
    else {
        $json = json_decode(file_get_contents('test.json'), true);
    }
}


$time_end = microtime(true);
$time = $time_end - $time_start;

echo "Read the file {$x} times in $time seconds\n";
```

Gave me the results:
(memcached)
```
root@vagrant:/usr/local/submitty/GIT_CHECKOUT_Submitty# php -f test.php
starting test...

Read the file 100000 times in 33.770106077194 seconds
```

(read from file)
```
root@vagrant:/usr/local/submitty/GIT_CHECKOUT_Submitty# php -f test.php
starting test...

Read the file 100000 times in 95.975661039352 seconds
```
So definite benefit even if we initially just use it for stuff located in files.

**Comment by KevinMackenzie** [comment]
I was thinking about how to utilize caching for data in the database.  Users would be good to cache so we aren't `JOIN`ing users onto a bunch of different queries.  The Gradeable configurations would also be good to cache since they change infrequently as well.

For users, we would need to be careful to flush or update the cache when non-PHP code updates the User list.

We could cache Gradeables individually by id, but we often want to get all gradeables (i.e. for the nav page).  To avoid querying the database just to get a list of gradeable ids we could have a separate cache entry for 'all gradeables' that gets updated whenever any gradeable is modified, or we could have an entry for 'all gradeable ids' that only gets updated when gradeables are created / deleted.  Further investigation of the latency of the caching service would be required to see which is a better option.

If we rolled our own caching service, we could add some very basic query features that allow us to make one request to get: all gradeables, all users from certain registration sections, etc.  This also provides the opportunity to dynamically choose which data to keep in the cache.  For example, we could keep all users and all gradeable configs in the cache, but use a caching strategy (i.e LRU) to determine which graded gradeables are kept in the cache.  This would reduce disk reads while grading.

Due to the nature of any text caching service, the PHP code would still have to handle cache misses, but we can handle this in an object-fetch layer that would abstract using db queries vs the cache.  We would face numerous different race conditions as well.  Since the plain-text of the cache gets completely overwritten every time we update it, if two users are adding marks to a gradeable at the same time, both marks will be added to the database, but the cache may only reflect one of these changes.  We would face similar issues with any concurrent modifications to a subset of the 'gradeable' or 'graded gradeable'.    This could be solved by breaking up the cache in a way that reflected the database tables, but this will be complex to reconstitute.

**Comment by KevinMackenzie** [comment]
I did some testing and in the grading details page, caching the users does not significantly reduce page load time (1000 students in the course).  It does allow us avoid `JOIN`ing user / team data every time we need it without resulting in O(n) queries.

**Comment by MasterOdin** [comment]
Closing this as it's a theoretically a nice thing to have, but given the amount of work to do this over theoretical gain, especially given that our web server doesn't struggle to do this, it doesn't seem worth it.
