### ISSUE TITLE
Add test for `package.json` and `package-lock.json` sync

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#10820]
**What problem are you trying to solve with Submitty**
`package.json` and `package-lock.json` can easily get out of sync if a reviewer does not notice that `package-lock.json` has not been regenerated when a new dependency is added.  This has happened several times, most recently in #10818.

**Describe the way you'd like to solve this problem**
It would be relatively straightforward to add a test to verify that `package.json` and `package-lock.json` are in sync, much like the DB check we already have.  This test could also be extended to check the Composer lockfile as well.

**Comment by rishabhknowss** [comment]
imo adding a script to check their synchronization (using git diff) and integrating it into a GitHub Actions workflow. The script will regenerate package-lock.json and check for differences.

i would like to work on this issue :saluting_face:

**Comment by rishabhknowss** [comment]
okay

**Comment by MasterOdin** [comment]
It's recommended that you use [`npm ci`](https://docs.npmjs.com/cli/v10/commands/npm-ci) in CI environments to install dependencies instead of `npm install` where the former will fail if the `package.json` and `package-lock.json` files do not match. That would probably be easier than doing anything else.

IIRC, `composer install` already does validation that the dependencies in `composer.json` match what's in `composer-lock.json`, and will throw an error if they don't match.
