### ISSUE TITLE
Errors submitting when a course has no released homeworks

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#116]
Even as a username on the dev team, I got the error "not a valid assignment", when submitted to an assignment, the only one in the class.json file, if it was not released.

**Comment by MasterOdin** [comment]
Could you attach the .json files used for configuring the class (namely, what is the value of 'dev_team'?

**Comment by bmcutler** [comment]
It was actually very similar to the default config that is created with create_course.sh.  I set all of the assignments to released=false.  I was in the dev_team list, so I could see the assignments, but when I tried to upload I got the failure.  I think there is a bug in the logic in public/controller/data_functions.php but I didn't investigate more thoroughly.  I just set released=true for one assignment and then I could submit to both.

**Comment by MasterOdin** [comment]
So you have two assignments and if both are not released, you cannot submit at all, but if at least one is released, you can submit to both? What happens if you submit to one, then un-release the assignment?

Seriously, it would help having the .json files from you (as I'm not sure where they're located on HSS machine) to more easily replicate this and check everything as the logic looks sound enough on first glance. If you don't want to post the stuff here, please email me the files.

Relevant lines: 

[data_functions.php#L131](https://github.com/RCOS-Grading-Server/HWserver/blob/master/public/controller/data_functions.php#L131) is your error message (and only place you'd have gotten it).

[is_open_assignment](https://github.com/RCOS-Grading-Server/HWserver/blob/master/public/controller/data_functions.php#L583-L601) returns false, then we throw the error message. This would mean either the assignment submitted wasn't found in $class_config or user wasn't on dev team.

 function [on_dev_team](https://github.com/RCOS-Grading-Server/HWserver/blob/master/public/controller/controller_functions.php#L4-L12) might be returning false

**Comment by bmcutler** [comment]
Yes :)  I studied the code before posting the issue and didn't see an obvious  bug in the logic either.  It was a problem with a fresh, out-of-the-box installation.  Once folks have standalone full installs up & running we can try to reproduce it on the non-live server.  I've made more changes to the files since then, so they are not helpful to share.

**Comment by bmcutler** [comment]
Melissa (& others), please try to reproduce this error.

**Comment by MasterOdin** [comment]
I just tried to reproduce this on the VM labstaff produced. My steps:
1. Run following commands:
```
sudo bash
addgroup csci1200
addgroup csci1200_tas_www
adduser developer csci1200
adduser developer csci1200_tas_www
adduser hwphp csci1200_tas_www
adduser hwcron csci1200_tas_www
cd /usr/local/hss/bin
./create_course.sh f15 csci1200 developer csci1200_tas_www
```
2. Navigate to ```/var/local/hss/courses/f15/csci1200``` and run ```./BUILD_csci1200.sh```
3. Navigate to ```configs``` and edit class.json to be:
```
{
    "dev_team": ["developer"],
    "upload_message": "Prepare your assignment for submission exactly as described on the course webpage.  By clicking $
    "assignments": [
        {
            "assignment_id":"lab01",
            "assignment_name":"Lab 1 Getting Started",
            "released":false,
            "ta_grade_released":false,
            "due_date":"2015-09-02 23:59:59.0"
        },
        {
            "assignment_id":"pythontest",
            "assignment_name":"CS1 Homework 1 Part 1",
            "released":false,
            "ta_grade_released":false,
            "due_date":"2015-09-02 23:59:59.0"
        }
    ]
}
```
4. Navigate to https://192.168.56.101/index.php?course=csci1200, submit to both assignments

Encountered no errors and both were picked up by grade_student.sh and executed.

**Comment by bmcutler** [comment]
This is still a bug on the system.  We just saw it this morning with the OpSys class.  Just 1 homework, configured, unreleased.   No assignments received.  When the dev team member tried to do a first test submit, nothing happened (after pressing submit, the selected file was cleared and nothing was received, the directories didn't exist). 

It might be a bug in the URL?  It said "assignment_id="  instead of "assignment_id=hw01".

Just changing it to released to "true", and the submission was successful.

(further testing not possible, folks had to run to lecture)

**Comment by MasterOdin** [comment]
It's more likely it's a bug in the URL that's a part of [this function](https://github.com/RCOS-Grading-Server/HWserver/blob/master/public/controller/controller_functions.php#L68-L82). Should add a "is_valid" type function for checking assignment_ids when parsing them.
