### ISSUE TITLE
fields set to -1 in setup_sample_courses is unnatural

### ISSUE THREAD

**Issue by MarisaPLee** [Submitty/Submitty#1170]
graded version would never be set to -1 in normal use

**Comment by MasterOdin** [comment]
Agreed. This field should be nullable. We should also add a foreign key constraint between gradeable_data and electronic_gradeable_data on the graded_version as then we can make it such that `null` is "no version", else it'll be a number that ties to the above table.

**Comment by holzbh** [comment]
Until this is rectified, generating grade summaries fails in [GradeSummary.php](https://github.com/Submitty/Submitty/blob/master/site/app/models/GradeSummary.php#L80) because

`$autograding_score = $gradeable->getVersions()[$gradedVersion]->getNonHiddenTotal() + $gradeable->getVersions()[$gradedVersion]->getHiddenTotal();`

is trying to access an element in an empty array.

Right now the failure happens because graded version is -1 and active version is 0 in this case - happens on the first user (currently consix) in the first gradeable visited (grades_released_homework_onlytaPenalty), but is going to be a problem with most submissions, which are generated the same way in [setup_sample_courses.py](https://github.com/Submitty/Submitty/blob/master/.setup/bin/setup_sample_courses.py#L785-L791).

Whatever DB change is made, setup_sample_courses.py should be adjusted to keep consistent.
