### ISSUE TITLE
documentation for rainbow grades

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1257]

**Comment by holzbh** [comment]
Initial notes:

1. "HWReports, CSV Reports, and Grade Summaries"
   Click "Generate Grade Summaries"
   Should get green box that says "Successfully Generated GradeSummaries" - it disappears after a few seconds.
       If page isn't still loading, probably means a success?

4. For dev instructions, need a -r in the scp

5. it should be <username>_summary.json

6. Currently we have a FIXME - this is bad! Need work here.
	Mention that there can be NO dangling commas.
	Everything inside a giant associative array.

	Support C-style comments, both // and /* */
	display_benchmark: optional. can be lowest_a- through lowest_d-, average, stddev, and/or perfect
		What do these do
	benchmark_percent: optional. can be used to change the thresholds for the lowest_a- etc. benchmarks

	gradeables: required. is the main array - each item in the array is an associative array for one syllabus bucket
	type: required, should match a syllabus bucket ("lab", "homework", etc.)
		List the buckets?
	count: required, how many assignments are in the bucket
	percent: required, the percentage (between 0.0 and 1.0) that this bucket represents in the overall grade
	ids: an array - each item in the array is an associative array containing information about a gradeable 
		id: required, string with the ID of the gradeable. Must match the Create/Edit Gradeable page, dir. etc.
		max: required, highest score possible (before extra credit)
		curve: optional, array with a- cutoff, b- cutoff, c- cutoff, and d cutoff
		released: optional, true or false. Behavior is still up in the air.

	final_cutoff: optional. associative array with "A": 93.0, etc.

	section: required. Associative array of sections to labels, labels can be any string.
	"1": "TA_name_1"
	"2": "In-Major Only"
	"3": "Remote Campus Class"

	messages: optional. Array of strings, all messages printed at the top of every student summary.

	iclicker_ids: optional. Does this even still get used?
	iclickers: optional. 

	use: optional. What's going on with this?

	moss: optional. Used for plagiarism penalties (should we even still call this moss?). Penalty might be capped to 1.0

	warning: optional. Adds a warning note (only seen by instructor) if the sum of scores in "ids" is less than "value"
		TODO: "value" is a very general term too...
	
	note: optional. Who sees this?

	manual_grade: optional. Associative array of username to associative array with "grade" and "note".	

7. Should be "for an upcoming exam"

7. Needs to reflect that this is now in the exam block instead of a stand-alone exam_seating
	Possibly add this part to 6 so it's clear where to add it?

8. Should be output_<month>_<day>_<year>.html   (there's a stray .html)
   Currently also produces a <student>_message.json - either we should stop that or report it happening.

**Comment by holzbh** [comment]
Should also make it a little more clear that the Submitty repo needs to be checked out as a whole - confusing for people unfamiliar with Git/Github. The link points to the RainbowGrades subdirectory which implies you can download JUST that directory. Due to the dependency on the syntax checker (to remove comments) that is in `grading/` this could be confusing the way it's currently written.

**Comment by holzbh** [comment]
iClickers are pretty specific - make a new heading further down the page to describe the iclicker fields/extra late days field.

**Comment by bmcutler** [comment]
Is this documentation on the webpage?  Can we close this issue?

**Comment by holzbh** [comment]
More or less. There's an open issue on the documentation repo for the extra late days field (I'll do it this weekend), but everything else is taken care of. We don't need this issue open still.
