### ISSUE TITLE
Add histogram visualization for instructor/ta to monitor assignment

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#136]
Add a script or maybe even a webpage to allow instructor/tas to view # of submissions for a specific homework, average/max grades, detect problems with a test case (if no one is getting full credit), etc.

**Comment by bmcutler** [comment]
Beverly -- Assigning to you, this is related to the figures we were discussing for the poster.  2 birds with 1 stone!

**Comment by sihsob** [comment]
Do you have any tips for how to start?

**Comment by MasterOdin** [comment]
Your best bet is to write a script (I'd suggest python since it has builtin JSON library and way easier counting of files in a directory) that generates these statistics that then are saved as an html page or something.

Counting the number of submissions should be fairly straightforward in this case (google this and you'll get a ton of SO answers on it), and then getting the statistics per testcase just requires you to parse submission.json for the active assignment (gotten from user_assignment_settings.json in the submissions directory) as it contains points for any given testcase. You could then compare that against the hw01_assignment_config.json file.

**Comment by bmcutler** [comment]
To start I'd recommend something simpler.  Check out the logs in /var/local/hss/autograding_logs/*.txt

(You will need a working installation and run a bunch of test submissions.)

You can gather alot of numbers just by 'grep'ing the log files.  
(Not down to the detail of per test, but that's not first priority.)

**Comment by sihsob** [comment]
Okay I'll look into both options. I am still working on getting a working installation of the server though. For now would it be okay to just print the results to a text file that tas/instructors could just open? I am unfamiliar with the ta grading side so I'm not sure how to incorporate that in.

**Comment by bmcutler** [comment]
Yes, work in stages.  Collect the data (plaintext or .csv, etc.)  Experiment with plots that you'll use for the poster.  Automate the generation of these plots (gnuplot or other tools can be automated).  The last step is to figure out how/where to display these to the TA/instructor, or even students :)

**Comment by sihsob** [comment]
Look at issue #201 for a more encompassing description of what statistics to show - this issue refers the TAGrading side

**Comment by bmcutler** [comment]
duplicate to #201
