### ISSUE TITLE
Lab Checkpoint Data Entry bugs

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1428]
@holzbh has reported.   details unclear at this time.  unknown what is necessary to reproduce.

**Comment by bmcutler** [comment]
Seems to be that clicking on the user's name to quickly give them all checkpoints is broken.  Those checks are not saved to the database.  Individually checked checkpoints are saved.

**Comment by holzbh** [comment]
I was giving checkpoints manually but I think in most cases it was 2-3 checkpoints at once, so this is the same sort of behavior. It's probably worth clicking 1,2,3 in quick succession as well once we figure out a fix, or not allowing the user to do so if that's going to be a problem.

**Comment by MarisaPLee** [comment]
The issue is from #1195. We previously had a similar race condition in saving to the database that was solved by saving components individually (instead of a whole row at once). #1195 introduced the same problem, but in the javascript. We should go back to saving components one at a time, and implement checking off all checkpoints at once separately.
