### ISSUE TITLE
editing student data requires the field of preferred name not to be blank

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1441]
This field should be allowed to be blank.

**Comment by pbailie** [comment]
I ran into this while examining/testing input validation regex's for the CSV upload and manual entry form (parallel to #1425 which I had been asked to correct in my last meeting with @bmcutler).

Anyways -- this bug is found in `/site/app/controllers/admin/UserController.php` line 106:
```php
if (isset($_POST['user_preferred_firstname'])) {
```

`$_POST['user_preferred_firstname']` will always be "set", even when the field is submitted as blank.  You also need to check if the field is empty or not.

So one possible correction is
```php
if (isset($_POST['user_preferred_firstname']) && !empty($_POST['user_preferred_firstname'])) {
```

If you don't mind, I can include this fix in my branch "improve_user_entry_validation" as I have already tested this solution and it seems to work OK.
