### ISSUE TITLE
Write more test cases for submitty_count

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1458]
For all supported languages
For node/token/function

Put them in more_autograding_examples?

**Comment by MasterOdin** [comment]
I'd rather have this done within AnalysisTools when we build the scripts since then we would catch bugs and things earlier in the process and allows for separation of concerns (So you just have to worry about "This is test is failing because submitty_count is wrong" and not "Is submitty_count wrong or is autograding messing up?"
