### ISSUE TITLE
Submission file size too big -> "Invalid CSRF token"

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1514]
This is the wrong error message!  

This is happening on 2 different live installations.
It previously would give a good error message about the size being bigger than allowed, and giving those numbers.

**Comment by MasterOdin** [comment]
It's probably because you're uploading a file that is so large (plus maybe some other smaller files?) that in combination with the other `$_POST` data, exceeds PHP's [POST_MAX_SIZE](http://php.net/manual/en/ini.core.php#ini.post-max-size) and so the whole `$_POST` array gets destroyed and hence it fails the CSRF token check. However, it's probably worth validating what the recommend memory settings are for Submitty and making mention to them within the documentation.

I suppose we want to add a new check in front of any method that involves uploading to at least check that `!empty($_POST)` and if that is the case, output an error message about the file size.

More details: https://stackoverflow.com/a/11476573/4616655

**Comment by bmcutler** [comment]
I don't know how big too big is (I haven't attempted to reproduce), but students are uploading "a few image" in my course, or large video files in the image processing course and hitting this message.   An appropriate error message is essential.
