### ISSUE TITLE
rotating sections assignment is buggy

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1683]
students who were assigned to a rotating section, but have since dropped (registration section = NULL) are not getting removed from the rotating section, even when "remove dropped students" is checked, or when "redo rotating sections completely" is checked.

**Comment by MasterOdin** [comment]
Should be able to just set rotating_section to null [here](https://github.com/Submitty/Submitty/blob/master/Docs/student_auto_feed/submitty_student_auto_feed.php#L530) in the autofeed?

**Comment by pbailie** [comment]
The auto feed only connects to the 'master' database, which does not have a field for rotating_section.

**Comment by MasterOdin** [comment]
Oh yeah, that would be why (silly me).

So I guess we may be forced to bubble up that field to the master database in the `courses_users` table to support this as the only other option would be to add a trigger or something to the course database such that if registration is null, then make rotating null, but that feels like that'll have bad unintended side-effects.

**Comment by bmcutler** [comment]
Adding to original bug report...  trying to reproduce the situation in vagrant was unsuccessful.  It appears to work correctly, but is broken for a live course.  We aren't sure what's different.  I suspect  the error checking is insufficient and we are seeing the green popup claiming sections have been adjusted but in truth, something is broken and nothing has been updated.

**Comment by pbailie** [comment]
This might be it
---
- Testing with my manually setup test VM (not vagrant).
- Testing with Master branch commit c94cf3f (Jan 31 2018 @ 11:13PM EST)
- Testing with _a copy_ of the live course data.
1. The first option: "Only remove unregistered students from rotating sections" will call
[`/site/app/controllers/admin/UserController.php line 236`](https://github.com/Submitty/Submitty/blob/c94cf3f6bc8a5e3c3ca9c6d8496775790790d829/site/app/controllers/admin/UsersController.php#L236)

   ```php
   $this->core->getQueries()->setNonRegisteredUsersRotatingSectionNull();
   ```
2. The second option: "Remove unregistered students from rotating sections and put newly registered students into rotating section with fewest members" will call **_the same_** database object method as above, except located [`on line 279`](https://github.com/Submitty/Submitty/blob/c94cf3f6bc8a5e3c3ca9c6d8496775790790d829/site/app/controllers/admin/UsersController.php#L279)
3. The third option: "Redo rotating sections completely" will call a different object method
 [`on line 267`](https://github.com/Submitty/Submitty/blob/c94cf3f6bc8a5e3c3ca9c6d8496775790790d829/site/app/controllers/admin/UsersController.php#L267)
   ```php
   $this->core->getQueries()->setAllUsersRotatingSectionNull();
   ```
   followed with
   ```php
   $this->core->getQueries()->deleteAllRotatingSections();
   for ($i = 1; $i <= $section_count; $i++) {
       $this->core->getQueries()->insertNewRotatingSection($i);
   }
   ```
   so that all users are completely reassigned a new rotating section _after_ their rotating section is set to NULL.

---

The SQL command called in options 1 and 2 is found
[`site/app/libraries/database/DatabaseQueries.php line 831`](https://github.com/Submitty/Submitty/blob/c94cf3f6bc8a5e3c3ca9c6d8496775790790d829/site/app/libraries/database/DatabaseQueries.php#L831)
```sql
UPDATE users SET rotating_section=NULL WHERE registration_section IS NULL AND NOT manual_registration
```
In order to set `rotating_section` to NULL, this query requires
1. a student be dropped (`registration_section` is NULL)
2. the `manual_registration` flag be FALSE.

Otherwise, `rotating_section` remains unchanged.

In my test with the live course data, all of the dropped students who won't move to the NULL `rotating_section` do have their `manual_registration` flag set to TRUE.  However, these same students are **_NOT_** tallied under "Non-registered Students" on the rotating sections page.  I see this column as empty.

---

But if we are going to make a change that all dropped students (regardless of `manual_registration` status) should be set to the NULL `rotating section`, the SQL command should read
```sql
UPDATE users SET rotating_section=NULL WHERE registration_section IS NULL
```
which is removing the `manual_registration` is FALSE condition.
