### ISSUE TITLE
Better error message when adding a duplicate student

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1718]
If the instructor attempts to add a student who is already in the course...  we get a bad/confusing exception error.  Make this a friendlier error.   Make sure other errors from this page are reasonable as well.

**Comment by rachitjain123** [comment]
Hey , I would like to work on the issue , I am not able to find the source code where it is implented, can you tell me where is the file which has implantation for it ?

**Comment by AasheeshT** [comment]
hey everyone, i would like to work on this issue , please assign me this issue.

**Comment by Sayak9495** [comment]
This is seems fairy simple to me. Kindly assign me to this issue. And what kind of friendlier error message should I update. Currently the error message is ('User already exists! Hit enter on any question to use existing value for that field.').

**Comment by kenzhemir** [comment]
Hi!
I'm interested in this issue.

#### Steps to reproduce the issue
1) Login to the system as instructor
2) Navigate to students list of some course, where at least 1 user exists
3) Click "New Student" button
4) Fill the form, but enter "User ID" of existing user

#### Expected behaviour
Error message pops up, saying "A user with that ID already exists"

#### Actual behaviour
We get Server Error page with DatabaseException
```
Oh no! Something irrecoverable has happened...

app\exceptions\DatabaseException (Code: 0) thrown in /usr/local/submitty/site/app/libraries/database/AbstractDatabase.php (Line 175) by:
            throw new DatabaseException($pdoException->getMessage(), $query, $parameters);


Message:
SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "courses_users_pkey"
DETAIL:  Key (semester, course, user_id)=(s18, development, aphacker) already exists.

Strack Trace:
#0 /usr/local/submitty/site/app/libraries/database/PostgresqlDatabaseQueries.php(109): app\libraries\database\AbstractDatabase->query('
INSERT INTO courses_users (semester, course, user_id, user_group, registration_section, manual_registration)
VALUES (?,?,?,?,?,?)', Array)
#1 /usr/local/submitty/site/app/controllers/admin/UsersController.php(118): app\libraries\database\PostgresqlDatabaseQueries->insertCourseUser(app\models\User, 's18', 'development')
#2 /usr/local/submitty/site/app/controllers/admin/UsersController.php(20): app\controllers\admin\UsersController->updateUser('students')
#3 /usr/local/submitty/site/app/controllers/AdminController.php(53): app\controllers\admin\UsersController->run()
#4 /usr/local/submitty/site/public/index.php(225): app\controllers\AdminController->run()
Extra Details:
query: 
INSERT INTO courses_users (semester, course, user_id, user_group, registration_section, manual_registration)
VALUES (?,?,?,?,?,?)
parameters:
s18
development
aphacker
4

true
```

Error comes from /site/app/controllers/admin/UsersController.php line 118 (Actually, whole conditional statement in lines 106-121). 
This block of code was added in #1487, and it has wrong conditional, which passes, when you want to add a new user with the same ID number. I guess, what author meant to do is
```
not: elseif ($_POST['edit_user'] != "true" && $user !== null) {
but: elseif ($_POST['edit_user'] == "true" && $user !== null) {
```

I guess, the whole code between lines 100-121 is unnecessary, because rest of the function implements the same functionality, so in my fix above, I just delete all those lines.
More tests required
