### ISSUE TITLE
Allow full access graders to upload for student

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1724]
Original Issue:
Allow full access graders to do:
upload for student 
& bulk upload 
& matching of upload to student

Re-write after further discussion:

We want to:
* Allow Full Access Graders to perform bulk uploads and then assign those uploads
* Allow Full Access Graders to upload for a student regardless of what section the student is in and whether or not they are assigned to that student.
* Allow Limited Access Graders to perform bulk uploads and then assign those uploads.

We also want to have a discussion about whether or not bulk upload should be its own gradable type like electronic file or checkpoints.

**Comment by yashjainpro** [comment]
i am interested in this issue

**Comment by vladan-jovicic** [comment]
Hi,
according to my research about submitty, in order to solve this issue, we need to allow users with group < 3 (i.e., full access graders) to submit instead of students. My idea was to show the form for uploading (with options "Make Submission for a Student" and "Bulk upload") which is the same for users with group < 1 (i.e., admin access) and users with group < 3. This can be done by changing HomeworkView.
However, this simple solution failed two checks (please, see #1784 ). Any suggestions about this?

**Comment by bmcutler** [comment]
Let's change this...  want limited access graders to have this ability too
