### ISSUE TITLE
Warning When Using More Late Days Than A Student Has

### ISSUE THREAD

**Issue by RylanOC** [Submitty/Submitty#1754]
When a student tries to submit an assignment 3 days late when they only have 2 late days, they should be warned.

**Comment by RylanOC** [comment]
Add a banner at the top of submission page displaying the number of late days that a student has, instead of assuming that they already know.

**Comment by bmcutler** [comment]
@RylanOC Note that the late days for an assignment might not be "charged" until the homework grade is finished (the TA has added their piece).  It doesn't appear in rainbow grades (a cause for confusion in students since the late days count does not include the most recent homework).  It may be a factor in the php code as well.
