### ISSUE TITLE
Stats on Forum Usage

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1793]
We'd like a page viewable by instructors and full access graders (not students or limited access graders) with stats on participation in the forums.

Probably a separate numbers for count of new threads, and count of posts in reply to threads
Perhaps also separating posts that are/aren't anonymous.
Probably want a list/table sorted with top participators at the top.

Assigning both Jared & Andrew.  Jared should do most of the work?

**Comment by bmcutler** [comment]
Maybe it can have a visualization/histogram...
but mostly we want the table, that we can copy paste from.
Perhaps being able to download a .csv would be nice.

**Comment by bmcutler** [comment]
Also...  its going to be important to add endorsement of each post (by teaching staff)
and a count of 'this was helpful' by other students.
and including this in the stats
(lots of unendorsed or non helpful posts don't make someone a top participator)

**Comment by ndixita** [comment]
Can also statistics parameters like: total posts, total contributions, total instructor responses, total student responses, average response time, and also a list of top 10 students sorted in decreasing order by their valuable contributions to the discussion (this parameter might be useful in case the instructor wants to give bonus marks to students for actively discussing topics on the forum)

**Comment by chetan9489** [comment]
I want to contribute to this thread, please guide me!
Where should I start?

**Comment by thatCode-Psy** [comment]
@chetan9489  I haven't gotten the page set up yet. I do not think this is a large enough project at the moment for multiple people since there is not that many statistics to use. As of now, the stats that we are interested in are the amount of "replies" by each user (along with timestamps), the amount of new posts by each user, and the amount of "last replies" in threads by each user. If you want to come up with any way to visualize this data or any other stats that we can extrapolate from this, that would help. Other than that, I don't really have that much to give.

**Comment by bmcutler** [comment]
closed with #1859 and #1898
