### ISSUE TITLE
Master->Course DB trigger for nonexistent registration section

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1997]
As discussed in our meeting today, related to #1293 and #1963 (Instructor UI for add/delete registration sections).

**Comment by MasterOdin** [comment]
I think I'd like to surface the sections_registration table to the main Submitty DB with an appropriate trigger to insert/update/delete the section into the course DB. That way we could put that information into the navigation page, as well as better foreign key the columns in that DB (as right now we're relying on the trigger to enforce the consistency). We maintain our foreign key constraints, and Peter can query this new "master registration section table" while processing the autofeed to detect new sections or otherwise. 

I'm against attaching a row creation to the trigger as it basically removes the usefulness of the foreign key and prevents really any sort of data consistency in the DB as any "wrong" registration section that gets inputted will happily be made into a new section, whether we want it to or not, unless we now enforce the foreign key constraint purely within the code.

The table definition I'd propose would be:
```
CREATE TABLE courses_registration_sections(
    `semester` character varying(255) NOT NULL,
    `course` character varying(255) NOT NULL,,
    `registration_section_id` INTEGER NOT NULL
)

ALTER TABLE ONLY courses_registration_sections
    ADD CONSTRAINT courses_registration_sections_pkey PRIMARY KEY (semester, course, registration_section_id);

ALTER TABLE ONLY courses_registration_sections
    ADD CONSTRAINT courses_registration_sections_fkey FOREIGN KEY (semester, course) REFERENCES courses(semester, course) ON UPDATE CASCADE;
```

**Comment by pbailie** [comment]
@MasterOdin 
> I'm against attaching a row creation to the trigger as it basically removes the usefulness of the foreign key and prevents really any sort of data consistency in the DB as any "wrong" registration section that gets inputted will happily be made into a new section, whether we want it to or not,

I'm not sure what you mean by a "wrong" registration section.  The registration section is part of a valid student record that is being upserted.  That registration section _needs_ to exist, so it really can't be "wrong".

As it currently stands, if that registration section doesn't exist, the student record can't be upserted.  (this may be indicative of a suboptimal entity-relationship, but that's a discussion for another time)

Also, the `sections_registration.sections_registration_id` column is not referencing any other tables, so any insert performed with a "wrong" (albeit "not null") datapoint, by either modifying `sync_courses_users()` or creating a new 'master' table with its own trigger, will be unconditionally accepted.

**Comment by MasterOdin** [comment]
By "wrong", I mean that we've been using a central source of truth to ensure that the registration_column has been correct, which up till now has been the sections_registration table in each course DB (and then enforced by proxy into the master DB via the trigger). If we modify the trigger such that the users table can insert rows into that table at will, it's no longer a source of truth as any bug in the code dealing with registration sections couldn't hope to be caught by the DB really.

Granted, we could still have bugs in the code that populates the registration sections, but that's a lot smaller vector than "anything that touches the master users table".

> Also, the sections_registration.sections_registration_id column is not referencing any other tables, so any insert performed with a "wrong" (albeit "not null") datapoint, by either modifying sync_courses_users() or creating a new 'master' table with its own trigger, will be unconditionally accepted.
That column is our point of truth. There's plenty of columns that act as the point of truth (like any pretty much any column in any of the table's in the master DB. That's fine. But by requiring us to change that table (or a newly attached table in the master DB), it's far more explicit a step than just "anything that modifies the user table", and one I'm more comfortable with.
