### ISSUE TITLE
User Feedback: Hidden Test Cases

### ISSUE THREAD

**Issue by jungj5** [Submitty/Submitty#203]
A fair number of students reported in the survey that they would like to see the hidden test cases. Although we don't want to show them these test cases before the homework is graded, we can consider showing them/explaining these cases after the homework has been graded. It would allow the students to know what they did wrong and learn from the mistake. It would also teach them to check for these types of cases in future coding practices.

**Comment by sihsob** [comment]
That's a really good idea!  It can be something configurable by the instructor if they really don't want to release those, but having the option there is nice.

**Comment by bmcutler** [comment]
Because creating a new homework assignment and new hidden test cases is time consuming (and thus may be reused in future semester), the instructor may not wish to reveal the full details of the hidden test case.  

It makes sense to provide some options for hidden tests once TA grades are released:
* full reveal (like a normal test case)
* a general instructor written description (a few words or a short paragraph) of the test case, including common errors
* an automatic error message specific to why the student lost points
* just the points awarded for the hidden test are revealed [what currently happens]

**Comment by laprej** [comment]
Maybe we can color code it?  Green if it passed?  Right now it's just a grey "Hidden" button.

**Comment by bmcutler** [comment]
Also...  let's have an option that the test cases isn't even visible at submission time (to allow instructor to avoid revealing the title or even the existence of the hidden test).  We already have the flag that the php webcode will use:
           "view_testcase": false
We just need to connect an instructor-written config option to this setting.

**Comment by bmcutler** [comment]
Instructors now have an option to reveal hidden test cases after TA grading is released.
