### ISSUE TITLE
User Feedback: Differences in Dr. Memory Output

### ISSUE THREAD

**Issue by wonga6** [Submitty/Submitty#205]
From the "Other feedback about the server" comment section of the homework server survey: Dr. Memory report returns an OK on the student's computer but on the server shows memory errors. (Also saw this in office hours too)

**Comment by sihsob** [comment]
Is it because it's incorrectly showing memory errors, or is this a case of "works on my machine but not on the server"?

**Comment by Mijumaru3** [comment]
Both? When the program ran with Dr. Memory on the student's computer there were no memory errors. But when the server ran the program with Dr. Memory there were memory errors (there was a post on LMS about this too).

**Comment by sihsob** [comment]
Seems more like a DrMemory error?  Maybe someone can try to replicate this issue and then see if it's a student code issue.

**Comment by Varlathass** [comment]
I remember having this issue too back in the day. It usually wasn’t a Dr. Memory error. I think there was usually something wrong with uninitialized values or something but I was always able to fix it. (though it was quite annoying)

**Comment by sihsob** [comment]
So I guess it's more of a works on my computer but not the server. I can look into improving the messages to help students debug (similar to the other issue open on error messages)

**Comment by bmcutler** [comment]
It is likely buggy code or code relying on unspecified/undefined behavior and differences in operating system/compiler/STL implementation rather than a Dr. Memory bug.

We should improve our messages to students, and give them suggestions for debugging.

Also, it would be nice to add a feature to automatically run Dr. Memory on the students code when there is a memory error or other symptom of memory corruption (even if Dr Memory output is not part of the grade.)

**Comment by bmcutler** [comment]
New goal for this issue:  Dr Memory output and Valgrind output should have specific, built-in, automated graders.  Similar to the Emma and JUnit graders.  Also think carefully about how to prevent cheating by simply output the message that we search for "NO ERRORS FOUND", etc.

**Comment by bmcutler** [comment]
Closed with #897
