### ISSUE TITLE
Page title

### ISSUE THREAD

**Issue by CouleeApps** [Submitty/Submitty#2169]
Currently the page title is always _just_ the course name. We may also want to include the current page and/or other information

**Comment by bmcutler** [comment]
@pbailie 
Are there any VPAT rules/guidelines about page title?

**Comment by pbailie** [comment]
After some additional review on this topic — I believe the best course of action is to form the `<title>` to state the name of the service ("Submitty"), the course, and the current page.

For example, if a student were logged into course CSCI1000 (Intro Programming) and reading in the discussion forum, the title could be:
```html
<title>Submitty CSCI1000 Discussion Forum</title>
```

Or

```html
<title>Submitty Introduction to Programming Discussion Forum</title>
```

The underlying issue is that the `<title>` needs to be convey what the user is accessing, unambiguously.  Using the three elements ("Submitty", course, and page), we can convey precisely what the user is accessing.  This becomes especially important if a user has opened an ocean of tabs, some of which are in various courses/parts of Submitty.
