### ISSUE TITLE
Fix broken grading view on Gradeable with no manual grading

### ISSUE THREAD

**Issue by CouleeApps** [Submitty/Submitty#2339]
Reproduce: Try grading the autograding only Gradeable in the sample course. You get to a blank grading page which throws lots of errors when you try to do anything.

Should we:
- Stop graders at the details page
- Allow graders to open the grading page but hide the grading panel

**Comment by bmcutler** [comment]
This is the only way to view the autograding results & submissions files of a student to help them debug.  So we want to let them onto the grading page.  (Instead of "grade" or "regrade" on the navigation page it should say "view submissions")

The summary & details pages should still be there with stats & info.

When you click into a particular student, just hide the rubric/grading panel.

**Comment by bmcutler** [comment]
closed with #2386
