### ISSUE TITLE
Consistent JSON responses

### ISSUE THREAD

**Issue by KevinMackenzie** [Submitty/Submitty#2362]
As outlined in http://submitty.org/developer/json_responses

We need to go through all of the pages that return json responses (i.e. ajax handler methods) and make sure that they conform to our standard on how json responses should be structured.  As of now, it is up to the developer per controller as to how these responses are structured.  

This issue also would mean removing any non-json text from the response.  For example, calling `addErrorMessage` will contaminate the output with HTML (see `ElectronicGraderController.php`).

Complying with this spec involves changing the controller code and the JS that calls these routes (via ajax)

All places that return JSON violate this spec in some way, but I'll list them anyway:
[ ] AdminGradeableController
[ ] GradeableController
[ ] LateController
[ ] UserController
[ ] Forum
[ ] ElectronicGraderController (*almost* complies, i.e. ~~`failure`~~ -> `fail`)
[ ] SimpleGraderController complies with the spec, but doesn't exclusively return json (sometimes redirects)
[ ] SubmissionController

**Comment by zjxiaohan** [comment]
@MasterOdin 
I tried to look into this issue before, and I found it confusing to distinguish "fail" and "error". Instead of our current standard, now that we are going to implement REST API, what about completely using "success" and "fail" (or "error") plus HTTP status code instead of three types of responses?
