### ISSUE TITLE
Fix not being able to set timezone on Edit Gradeable page

### ISSUE THREAD

**Issue by KevinMackenzie** [Submitty/Submitty#2771]
In nearly all situations, when updating the date properties of a gradeable, the time zone for that date is not saved.  Peculiarly enough, the `Now` button in the datetime picker _does_ properly update the time zone, but no other means of changing the date value does.

**Comment by bmcutler** [comment]
Also... Investigate what is going to happen when a gradeable spans a daylight savings boundary.  Ideally dates chosen before and after this boundary will auto-default to different offsets from UTC.   First just document what happens.

**Comment by KevinMackenzie** [comment]
Attempting to change the dates in the psql console, along with the [PostgreSQL documentation page](https://www.postgresql.org/docs/9.1/static/datatype-datetime.html), supports the fact that the timezone provided when setting values in the database is not stored in the database.  You can tell simply by looking at the data breakdown for each type, but executing the following line in the psql console should be more obvious: 
`SELECT '2011-01-01 00:00:00+03'::TIMESTAMP WITH TIME ZONE;` 
```
      timestamptz       
------------------------
 2010-12-31 16:00:00-05
```

That being said, some of the gradeable dates have the `-04` timezone, and some have the `-05` timezone in my database, but this is because postgres automatically accounts for daylight savings time when loading the data.

Our date-time picker does _not_ account for daylight savings time since its a date picker with a time picker tacked on.  If we can get this supported, the daylight savings time boundaries shouldn't be an issue.

**Comment by MasterOdin** [comment]
So in reading about this, it's more that PostgreSQL stores all times internally as UTC and then when queried returns them in the timezone as specified by that particular session (which then defaults to a value in a conf file), which is largely fine. The date you selected and the date returned are the same, and that we should be transforming whatever we pull out of the DB via the timezone specified within our config anyway (to protect against the fact the DB may be specified to have a different timezone than we use in the code). 

I honestly don't care what exact timezone each string is stored in the DB (though it's either the one we're attempting to insert or just UTC) as this was primarily just so that Barb would have an easier time of understanding it if looking at the DB directly. So long as what we put into the DB has a timezone attached and what we pull out has a timezone attached, then it's all gravy as going in, PostgreSQL can figure out what it may need to translate it as and then pulling it out, PHP can figure out the translation it needs to do to get it into the right timezone.

Similarly, what we want from the front-end is just to specify a timestamp (without offset) and then on the PHP side, attach it, a la:
```
$a = new DateTime("2018/08/20 10:00:00", new DateTimeZone("America/New_York"));
print($a->format("H:i:s"));
print("<br />");
print($a->getOffset()/60/60);

print("<br />");

$b = new DateTime("2018/12/20 10:00:00", new DateTimeZone("America/New_York"));
print("<br />");
print($b->format("H:i:s"));
print("<br />");
print($b->getOffset()/60/60);
```

which gives us:
```

10:00:00
-4

10:00:00
-5
```

so that an instructor in both cases assumes they're just putting in "10:00:00" and then we let PHP figure it out. The next step once this all is in place and working, is to then look at utilizing something like [moment.js](https://moment.github.io) to handle timezone change detection between timestamps since trying to figure this stuff out ourselves is a waste of time and effort.
