### ISSUE TITLE
grades_released_homework is missing all common marks

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2803]
Not sure when this started...  but this gradeable (and perhaps others) are missing common marks, including a no credit/full credit mark.

This makes editing the rubric from either instructor or ta interfaces (at least with PR #2751, that I'm about to merge) impossible.

**Comment by Fenn-CS** [comment]
@bmcutler I am able to edit this particular homework in it's current state.

**Comment by MasterOdin** [comment]
To give some context here, if you go to [Future (No TAs) Homework](http://192.168.56.111/index.php?semester=f19&course=sample&component=admin&page=admin_gradeable&action=edit_gradeable_page&id=future_no_tas_homework&nav_tab=2) and expand "Readme", you'll see three marks (outlined for emphasis):
![Screenshot 2019-07-09 22 35 18](https://user-images.githubusercontent.com/1845314/60936067-e3612000-a299-11e9-8f91-294a06e5056e.png)

On grades_released_homework, you get no marks starting out (to get things into a proper state, you have to hit "Add New Mark" twice, and then toggle the count up/down setting):
![Screenshot 2019-07-09 22 36 24](https://user-images.githubusercontent.com/1845314/60936118-0390df00-a29a-11e9-89b8-72afe94070a6.png)

which in turn causes some number of UI and other bugs. This is due to the fact that the yml file we're loading does not have any defined marks for that gradeable:
https://github.com/Submitty/Submitty/blob/1d0226d83163f270e6ef02ab93048af7c4b2e106/.setup/data/courses/sample.yml#L641-L659

Compare that to Future (No TAs) homework for example:
https://github.com/Submitty/Submitty/blob/1d0226d83163f270e6ef02ab93048af7c4b2e106/.setup/data/courses/sample.yml#L10-L73

The simple fix is to just define a `marks` object under the grades_released_homework's components, but it should be decided if we also want to make `setup_sample_courses.py` do something as well when it's loading these yml files, such as if it detects a electronic gradeable, and that it has no marks for a component, crash with a meaningful error message, or maybe just output a warning and silently fill in some sort of default mark, or etc.

**Comment by Fenn-CS** [comment]
Thanks for the explanation Matt, going by the last method is better as we discussed on Hangouts, it would be more robust if those non-existent objects are created in `setup_sample_courses.py` with some logging but not termination.
