### ISSUE TITLE
Use a sub-folder within git checkout for submission

### ISSUE THREAD

**Issue by prestoncarman** [Submitty/Submitty#2925]
In our class we have one git repository for the whole quarter and have separate folders for each assignment. It would be nice to specify the path with in the GIT repository to use for the assignment. You would only need one more piece of information, the path for the assignment.

**Comment by MasterOdin** [comment]
If I'm reading this correctly, you want to have the git folder not in `/var/local/submitty/vcs/git` but somewhere else on the same server? Or is this path unique per course?

**Comment by bmcutler** [comment]
No, I think he's suggesting that we not do a full checkout of the student's repo (or at least not store/archive the whole repo), but allow the instructor to specify a subdirectory within the students repo per gradeable.

We used to do this with SVN repos.  We had a subdirectory variable as part of the VCS config for each gradeable.  SVN supports checking out only a subdirectory (versioning is really per file with SVN).  And that was in many ways more convenient for instructors and students, fewer git repos to juggle per term.  GIT doesn't do this as easily, since versioning is across the whole repo.  It's quite doable to re-implement this feature.  It would be handled at the checkout/autograding/archive stage.

**Comment by MasterOdin** [comment]
Oh, rereading the original post and this, yeah, it does seem like it's taking a specific folder out of the checked out repo. 

Implementation I guess would be adding another setting to the gradeable creation page when selecting VCS that asks for a subdirectory? Or a list of subdirectories/files? (given that we're not using that field across tables, we can probably just have a serialized array into the field that gets unserialized when pulled out).

**Comment by prestoncarman** [comment]
@bmcutler You are correct. The repo could hold many assignments, but the subdirectory could specify a which assignment to use for grading. You may have to check out the whole repo, but only copy the subdirectory for the gradeable. @MasterOdin The additional information could be a set of file paths or just the directory those files reside.

**Comment by duncjo** [comment]
This issue has become more pressing for us as the changes to VCS over the summer no longer allow an arbitrary URL to be used for a gradable.  We now only have the option of using `base_url/gradeable_id/user_id` from what I can tell.  But our students all have a single repo per class and gradeables live in subdirectories.  So we really need `base_url/user_id/gradeable_id`.  Maybe I'm missing something, but I don't see how to accomplish that anymore.

**Comment by prestoncarman** [comment]
PR #7435 is the working code we have been using to allow students to submit homework in a sub-folder of their repositories. Let us know how we can improve it or any changes need to make so it can be brought into the submitty code base.

**Comment by IDzyre** [comment]
Completed in #9317
