### ISSUE TITLE
Grade Override: e.g. makeup exam data entry

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2982]
most of the class takes an exam with a complex rubric.
a couple students take a different exam as makeup, which the instructor grades outside of submitty.
Provide a way to specify just the total for each student as makeup.

possible database changes?
Perhaps a new table for grade override?
gradeableid, userid, score, string message
possibly also a scanned file?  (graded by hand?)

Then when displaying the grade, if there is an entry in the grade override for that student for that score, display that instead.

And grade summaries needs to use this too.

**Comment by bmcutler** [comment]
Repeatedly requested by instructors, this should be a priority to implement this summer
We could implement it in rainbow grades, but it might be nice to put in the website UI.  

How about a simple form (similar to late days & excused absense form).

Instructor selects a student, selects a gradeable, and then specifies:

a) a total score for the assignment... e.g. the student took a makeup exam and score 86 / 100.  Ignore the autograding/ta grading (if any) and just give this grade.

b) a point adjustment (positive or negative) for the assignment...  e.g. the student should get a +10 point adjustment on that homework because the autograding was broken and I can't easily fix the autograding.  We grade the assignment normally and then add 10 points.

c) a percentage adjustment (positive or negative) for the assignment.. e.g. the student submitted late, and my course policy is to dock them 20% for each day late.  We grade the assignment normally (autograding + ta grading) and then apply a -20%.

This design can also replace what we're doing in rainbow grades customization.json for incidents of plagiarism.

We can store this data in a new table, separate from the gradeable/components/marks, and just reference it when we do grade summaries to prepare data for rainbow grades.

Sound good?

**Comment by bmcutler** [comment]
@KevinMackenzie @holzbh @MasterOdin

**Comment by holzbh** [comment]
I agree that it makes more sense to do this Submitty-side instead of in Rainbow Grades. The first option at least solves the core problem but the other two options are often requested features as well that would be useful and I like the idea of having all three options as some sort of "grade adjustment" form.

Definitely worth keeping in mind especially for options b and c, that we'll want to reflect this on the View Grade page for the gradeable as well so the student has a consistent view. It can appear as just another TA mark called "Adjustment" or something?

I also think it would be nice to be able to store a comment (whether that's instructor-only or instructor-and-student-can-see-it) with each adjustment.

**Comment by bmcutler** [comment]
Yes, I agree it would be nice to have 2 optional (can be empty) string fields, one visible by students, one only visible by instructors.

And it would be nice to have for team assignments.  Usually everyone on the team gets the same grade, but this could be used to modify the team score for an individual if appropriate.
