### ISSUE TITLE
Investigate use of REST endpoints

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#300]
Should check if we can make available REST endpoints without being logged in to the server (the endpoint should involve the authentication). We should start with the very basic example of "Get All Open Assignments" and return that in an ordered JSON list. If that is possible, than we can expand it as need arises.

**Comment by MasterOdin** [comment]
So the front end of the system can start to support this as we've moved away from the apache authentication and moved into using sessions. We just need to make endpoints and discuss how we want to lay out the code and paths for this.

We most likely want to make an "API" controller, use some method to version it, and and then separate it out as necessary from there.

**Comment by MasterOdin** [comment]
We would want to rewrite the current controllers to have a better divide between "getting information" and putting it into the models. An example of this would be for getting graders we might want to separate the current method of `listGraders()` into `getGraders()` and `displayGraders()` where the first method would incorporate the first line and the second would incorporate the second two lines (a pedantic example). This way the api controller can utilize the former method and the web view can utilize both.

**Comment by prestoncarman** [comment]
I am researching how to interface with Submitty from other applications. A REST API would be a perfect way to make those requests. The comments posted here are from 2016. Do you still feel this approach to adding a REST API is the best way to proceed at this point in time?
- Adding a API controller
- Refactor the current methods into a get data and display functions.
- Building on your example, the endpoint could be a GET request to /api/v1/graders
What are your thoughts about using a library to help with the REST API details (routing, token authentication, etc.)?

**Comment by MasterOdin** [comment]
I'm not sure really what the best method here would be, and I've waffled through a couple different designs in my head over the years. Right now, I think I'd lean more towards having an `api.php` in `site/public/` with Apache setup to route calls to `submitty.example.com/api/<API_STRING>` into calling `api.php` and then having that translate the rest of the route into something Submitty could use. From here, I think modifying the existing controllers to always return something (and be able to set $core->output to a NullOutput so any view calls are silently just swallowed and then turn off redirect() happening). This would also make it increasingly possible to unit test our controllers 
and hopefully improve stability.

With regards to libraries, what would you have in mind? I'm familiar with a couple pieces of symfony, but would be interested to hear what else you might of used/heard good things about.

**Comment by prestoncarman** [comment]
Recently I worked with [Lumen](https://lumen.laravel.com/) a micro framework by Laravel. The process was fairly straight forward to set up and implement a REST API and connect it to models that required no SQL. The models have a faker class that can generate data, which was useful in creating tests. The framework handled the SQL code and URL routing. For basic resources, it was all done by the framework. The custom endpoints required additional information, as you might expect. The framework could run off its own PHP process and use a separate port.

I have not used Symfony, but it seems fairly popular. Here is a [comparison](https://thinkmobiles.com/blog/symfony-vs-laravel/) between the two.

* It would be nice to have [JSON Web Token](https://jwt.io/) support for the API.
* Do you think it would be helpful to have the API on a different port?

I like the suggested URL. We could add an additional options for the version `submitty.example.com/api/v1/<API_STRING>`,  if we think multiple versions might need to be supported.

**Comment by prestoncarman** [comment]
Should the REST API be implemented in PHP or Python? If you implemented the API in Python you could possibly in the future remove PHP completely and use Python and a web client (HTML, CSS, JavaScript, etc.) for the front end.
I was recently looking at Python frameworks used to build REST APIs and found two that seemed interesting: [Falcon](http://falconframework.org/) and [Hug](http://www.hug.rest/). Hug is interesting since you can make the API available to HTTP and CLI. A single code base could be used for both the command line and web front end. The testing would then cover the code behind both access points.

**Comment by MasterOdin** [comment]
We should really only commit to a python based API if as you said we were planning on completely ditching PHP. Given how development of Submitty works, and that it's not clear we could follow the [strangler pattern](https://blog.overops.com/strangler-pattern-how-to-keep-sane-with-legacy-monolith-applications/), I'm going to advocate against that course of action. 

Other than an entry point and maybe router, I'd like the API to use the same controllers as the existing site as it'll force us to also make them more easily unit testable while we're at it.

**Comment by zjxiaohan** [comment]
So since I am not that familiar with Submitty yet, I wrote a summary of the discussion above. Please correct me if I got anything wrong.

There are some data that could and should be exposed to the public. Currently, to get any data from Submitty, a user has to log in the system. Because users who are not logged are prevented from accessing any other controller than authentication. Setting up an API makes fine-grained access control possible, facilitates unit testing and benefits future possible developments of other applications.

Therefore, we need to modify some controller methods so that they always return, with regard to the set flag, either JSON data for API or the twig template. Besides, possibly, change the current authentication method (Database, PAM) to JWT, which has better scalability and accords with REST principles.

Proposed frameworks for constructing API are Symfony and Lumen.

**Comment by prestoncarman** [comment]
@MasterOdin Thanks for sharing the link for _strangler pattern_. I agree the REST API should share as much code as possible as long as it keeps things simple. 

@zjxiaohan I think that sums up the topics we have discussed.

One more thought about simplifying the code base while adding the REST API. It seems that the REST API may provide features that are not in the web front end or requires additional alterations to make it work properly. It may be helpful to used the controller code to implement the REST API and then create a modified web controller that uses the output from the REST API controller. Instead of having a single base that has two views: web and api. Create a base that supports the API and then build your web view on top of the API. Everything would still be in PHP and testable, but not force the API to conform to the web front end specific needs. One example: the web front end requires persistent state for logged in users while a RESTful API does not support maintaining state.

As we look to creating an API, here is a [Google Doc draft for a REST API](https://docs.google.com/spreadsheets/d/1V51fZM4ii8IxbhIPTj4wp3R5o8qKIXBy8fUi4H-QLY4/edit?usp=sharing). Please take a look. We can continue to edit and modify the API while its being developed. Use this as a launching point for discussion and adding more endpoints.

**Comment by Fenn-CS** [comment]
@ZishanHuang I think, what you got is "almost" it's not a matter of making it "public" I think it is a matter of making a *STATELESS API* where authentication is done every-time a request is made by passing a TOKEN. This is a better way of making APIs today.

**Comment by zjxiaohan** [comment]
@prestoncarman 

Thanks for your feedback. I agree that it is a better practice to separate API and web view, which makes things clearer. That being said, for the logged in state maintenance part, I would suggest switching to JWT now that we are going to build REST API.

Thanks a lot for creating the draft! I am looking into it.

**Comment by zjxiaohan** [comment]
@Fenn-CS 

Thank you for your comment. I definitely support the idea of authentication via JWT token and think it is better for the API. I was just trying to get the motivation of building an API in the first place. Based on the original post which says "make available REST endpoints without being logged in to the server", I got a feeling that Submitty needed to expose some data to the public.

**Comment by MasterOdin** [comment]
So, here is a summary of my thoughts at the moment:

1. Any REST API should be done such that it exercises most of the same codepaths that the web frontend uses. This allows for code reuse and a to also test our controllers along with having the API
1. Using a framework like Laravel or Lumen would be nice, but I think it may require a fairly large rewrite of our backend to put it into what they expect. Given our development resources as well, it may be that a transition might take the better part of a year (retiring just the old Gradeable model took about that long). Additionally, the lack of internal testing makes me apprehensive that we may accidentally break something. As such, I'm going to advocate against this approach for now (but leave the option open in the future after we have better testing coverage and such a transition would be easier).
1. For now, I think we can leave off the version string on the API. In the future, once the API is completely stable, and that we have many people relying on the API, we can properly version it then, but for now, it's probably unnecessary for the handful of users who might care to use it.
1. I agree with using a JWT, but that realistically, we probably just want to encode in it `user_id` and `api_key` and that we always check that against the DB (while also getting user info to do permissions checks). In the future, if we find that we need to "scale" and have implemented caching, we can revisit what we embed in these tokens.
1. Invalidating a token would therefore just be changing the `api_key` to something different. We do need some way to invalidate a token in the case that someone's token leaks.
1. The base of the web and API could be more or less the same with the exception of:
  1. how we check authentication
  1. how we output exceptions/fatal errors
  1. how we output our final result (HTML vs JSON)
1. To make the controller paths the same, I think I'd like to make it such that we have a concept of a "NullOutput" for the API such that all methods the controllers call on them just return trivially and then the controllers return whatever data they accumulated for the views
1. Have the API disable the ->redirect() method on core in some fashion and then just have a return after any redirect line in the controllers.
1. With the exception of the authentication controller, pretty much every other controller method I think should have an equivalent API endpoint.

**Comment by xprilion** [comment]
@MasterOdin 

About 

> 6. The base of the web and API could be more or less the same with the exception of:
> 7. how we check authentication
> 8. how we output exceptions/fatal errors
> 9. how we output our final result (HTML vs JSON)

I guess we could follow the guidelines set at - [https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md](https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md), something I have found very clear and complete. However, suggestions are welcome! 

And for the supporting of both API and non-API access to methods, is there any future plan of dropping entirely the non-API based access? If yes, maybe it would be good to have all the controllers just return JSON while the Views build the html from them, which could be skipped via a flag in the request. It would support the future possibility for a complete shift to stateless access to Submitty.

**Comment by zjxiaohan** [comment]
@xprilion Thanks a lot for your link!

For the second suggestion, I would suggest that we'd better first have both API and non-API methods (API and current controller methods), and then, after the API is done, see if we could shift completely to stateless access to Submitty.

**Comment by MasterOdin** [comment]
There is no plan to drop the web frontend of Submitty and it will remain the primary way for people to interface with it.

**Comment by zjxiaohan** [comment]
A diagram is needed to ensure that we are consistent on the overall design. @MasterOdin
