### ISSUE TITLE
forum thread list scrolling

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3032]
When you click on a thread from the list, the left thread list scrolls vertically to place the selected thread at the top.  This is confusing.  It would be better to not move the left panel scrolling, leave the clicked item approximately where it was.

**Comment by xprilion** [comment]
I assume we're looking here at a solution which allows the following - 

[1] User scrolls the thread list to a thread
[2] User clicks on it
[3] The thread maintains its position on the left panel 

If yes, we could probably bring in the usage of APIs to load the thread post, and not refreshing the page at all. This issue will be better addressed once we have an API for fetching threads. Since then, we can simply use Ajax to fetch the thread and load it into the view without any changes to the rest of the page. 

What are your suggestions @bmcutler @andrewaikens87?

**Comment by MasterOdin** [comment]
I do agree with the steps above of using AJAX to load the thread view once you click, but I do disagree with that it'd be using the API. The AJAX call should return HTML (that was generated via twig) that then gets used to show the thread.
