### ISSUE TITLE
VPAT -- Please Do Not Trap The Tab Key

### ISSUE THREAD

**Issue by pbailie** [Submitty/Submitty#3146]
The Tab key is integral to keyboard navigation, and therefore integral to web accessibility.

Some portions of Submitty's UI intends to trap the tab key into a control element (such as a textbox), preventing the tab key from navigating to another control element.  This _**will**_ severely interrupt a keyboard user's ability to properly navigate through Submitty's UI.

Please correct the UI so that the Tab key is _**always**_ usable to navigate through a page.

Here is a code example of trapping the tab key.  There could be more instances.
https://github.com/Submitty/Submitty/blob/c99b355092dd43cfae0babee2fce28e9c54d744b/site/app/templates/submission/homework/SubmitBox.twig#L334-L358

**Comment by pbailie** [comment]
@MasterOdin

Web accessibility isn't just a good principle, it is Rensselaer Polytechnic Institute policy.

As the tab key is _the_ navigation key, trapping it in any control element would cripple site navigation.  That would qualify as making a site "inaccessible", and therefore non-compliant with Institute policy.

You can have a look at the policy [here](http://policy.rpi.edu/policy/Web_Accessibility_Policy).

BTW, other Universities, at least in the U.S., will also have similar policies as web accessibility is compelled by federal law (as noted in Section 3 of Rensselaer's Web Accessibility policy)

**Comment by bmcutler** [comment]
Hi Peter,

There are cases where we are almost providing a code IDE for students.  As part of an in-class online quiz or lecture exercises the students might be asked to type a short Python program into a text box.  We then grab that code from the textbox, save it to a file and execute it.

Yes, of course, we need to have the default behavior of all textbox inputs (including a code IDE-like textbox) be accessible and not trap the tab.

But we also do want to provide a way to override and allow more natural code typing with tab in these boxes.  Writing python code without tab would be annoying to most users who are used to development environments where tab is second nature.  Even in writing a short essay with paragraphs with indentation, or a bulleted list it is important to allow natural lengthy typing (with 'enter' and 'tab') in one of these boxes.

Other web sites providing coding IDE's have certainly encountered this problem.  We should see how they've handled it.  (Some probably ignore assessiblility, but some hopefully have a good solution -- or at least a workaround).

I propose we add a switch somewhere on the page that when enabled will trap the tabs in the textbox.  The challenge is to label the option well so that new users will find it and be able to choose to enable it, and make sure that keyboard only users don't accidentally enable it and get stuck.

Barb

**Comment by drumilpatel2000** [comment]
It is better to provide toggle switch between `Tab for navigation` and `Tab for indentation`. This toggle switch can be toggled using shortcut for eg `Alt + w`'  so this site can be easily controlled using keyboard.

 
This is one of possible solution as suggested by @bmcutler .This can be easily implemented using `javascript` and It should be implemented to every textbox present in site by changing some codes in `server.js` 

@pbailie , @bmcutler  and @MasterOdin  Is this be implemented ?

**Comment by pbailie** [comment]
@drumilpatel2000: Since December, internal conversations I have had on this issue have concluded that the design concept of a toggle switch to be an insufficient implementation because it could interrupt natural navigation flow.

Instead, the discussions lead to using alternate keyboard shortcut to proceed out of a textbox control.  The ESC key was favored as this behavior to "escape" the textbox is also intuitive for console application users.

In early January, I created a prototype control for using a shortcut key to proceed from the checkbox.  Please review my prototype at http://www.cs.rpi.edu/~bailip2/ui_test.php  The prototype works with Firefox and Chrome.

I had invited RCOS and the disabled community at RPI to test and comment on the prototype, but have not received any commentary (the timing may have been bad as this was during semester-prep time).  As this issue has now resurfaced, I will resend that invite.

@drumilpatel2000, if you also know of anybody in a disabled computing community who may be interested in my prototype -- I also would welcome their feedback.  Thank you.

**Comment by MasterOdin** [comment]
I'm a fan of the use of "ESC" here to go forward rather than a toggle switch, and found your UI test to work in that regard.

For what it's worth, I don't think other code IDEs really bother with this problem and are fine with the decreased level of accessibility.
