### ISSUE TITLE
Support team submissions

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#317]
Allow submissions to be tagged to multiple students if they were working together. Right now we would require both students to submit the same code and then have graders grade the assignment twice. We should have it such that we can submit once per team and then grade once per team.

**Comment by bmcutler** [comment]
When marked by the instructor as allowing team submissions... 

Here's the straightforward design plan:

1. The assignment will be uploaded by a single team member, designated the team leader.

2. In addition to the file upload, the team leader must list the userids of all team members (without typos).

3. Each of the other team members must also log in, but instead of uploading files, they will indicate they are a non-leader for a team.  The will have to enter the userid of the team leader (without typos).  

4. A proper two sided matching is confirmed and visible to the non team leader.  The team leader also can see confirmation of matching for each team member.

5. Students can start a submission, then cancel it and indicate they are a non team leader (relying on the team leader to upload the files).

6. The team leader can change the membership of the team.  (anyone kicked off the team will see they are no longer matched).

7. TA grading will be similar to the current system.  Only the team leaders assignments will be graded.  Non team leaders data will be copied from the team leader (is it duplicately stored in the database?  Is it only generated when the homework report or grades summary is generated?  ...  design incomplete)

**Comment by bmcutler** [comment]
To close this issue, we'll focus on creation of teams and submission & autograding of team assignments.
