### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#318]
Creating this issue to track discussion of coding style of the project so we can come up with one style and stick to it a bit more closely.

Here's a wiki link for this topic as well https://github.com/Submitty/Submitty/wiki/Coding-Style-Guide

@bmcutler @pbailie

**Comment by bmcutler** [comment]
(I didn't read the linked/referenced external documents)

I disagree about a new line for the else statements.  I usually like to fit more logic onto the screen and avoid unnecessary newlines & vertical space bloat.

I'm ok with 80 characters per line as a guideline...   but we must allow it to be broken (sometimes arbitrary line breaks are more confusing than the inconvenience of horizontal scrolling or making your window wider).  Why mandating 60 char for comment? 

I'm ok with the variable names, function names, class names.

I don't understand the 3rd C++ header rule.

Google style guide link is broken?  (Has the C++ stuff even been edited since the original RCOS group?)

I think we should put the code through some auto-style/linters/whatever and discuss the results and revise the default for these tools if needed.

**Comment by gonsie** [comment]
The link for the Google C++ style guide is broken... is this the same one? https://google.github.io/styleguide/cppguide.html

**Comment by gonsie** [comment]
I agree with Barb about condensed if-else blocks: 

```
if (x) {
    // do something
} else if (y) {
    // something
} else {
    // something
}
```

I do not agree with a *required* 80-character-per-line limit.

Also, should there be a rule for global variables? I believe there many places in the code where all-caps are used to indicate global vars.

**Comment by MasterOdin** [comment]
We'll want to investigate the usage of tools to have code style checked and reinforced on pull requests. For this we'll have to investigate the usage of things like Code Climate, SonarQube, etc.

**Comment by prestoncarman** [comment]
It would be nice to have a standard for the project. I have noticed different styles through out the code base. Sometimes in the same file.

**Comment by MasterOdin** [comment]
Agreed. For new python files, we're using flake8 now to lint them, but there's still a lot of python code that is still not linted yet (and which I'd like to also start writing unit tests and such for as well while I'm at it).

For PHP, the main stopper here has just been finding the time to sit down and figure out the configuration of https://github.com/squizlabs/PHP_CodeSniffer to fit what we need. If you've got any knowledge of this or good material to look through, I'm all ears as its a bit complex to look through and figure out the rules here.

**Comment by MasterOdin** [comment]
Closing this as it's a meta-issue that hasn't seen any action in years. I've integrated a linter for PHP and Python to help ensure consistent style. If @bmcutler would like, I can look into adding something like [cpplint](https://github.com/cpplint/cpplint) for the C++ code.
