### ISSUE TITLE
Normalize data model for grading server

### ISSUE THREAD

**Issue by pbailie** [Submitty/Submitty#325]
Current database model is not normalized, and this will lead to data anomalies in the long term.  While working on issue #122, I will also map and normalize the database model to at least 5NF.  Code changes to grading server will be needed, but not before normalization is complete.

This work may run parallel to issue #174.

**Comment by bmcutler** [comment]
Just adding a note that when restructuring the database, it would be good to swap some names.  

We talked about replacing "rcs_id" with "user_id" to be less RPI specific.

In some other issues we talk about replacing "lab_section" with "registration_section" to generalize for courses that have recitations instead of labs.

Also, the use of the words "user" and "admin" are confusing.  What we really mean by "user" in the hwgrading code is "grader", and "admin" is "course manager".

There are certainly other things to rename.  Once we have a new design we can review & nitpick.

**Comment by MasterOdin** [comment]
I think we should separate out renaming columns from normalization especially in regards to the user/admin stuff just so this doesn't get dragged out unnecessarily.
