### ISSUE TITLE
Specify late day exceptions for a rubric that doesn't exist yet

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#328]
The current work-around is to create a dummy, empty rubric.  

But this is error-prone as the instructor might forget about the placeholder rubric and make a new rubric when they actually want to setup the questions & points.

**Comment by MasterOdin** [comment]
I think a better solution is waiting for when systems are merged and then the workflow would be:

1. Instructor creates assignment on server
2. Instructor creates a rubric for that assignment
3. Instructor adds late days exception (and this could be done before step 2)

I'm marking it "wontfix" (but leaving open and milestoning it for 1.0 release) since it's going to be indirectly fixed.
