### ISSUE TITLE
Create default category for discussion forum 

### ISSUE THREAD

**Issue by andrewaikens87** [Submitty/Submitty#3298]
Currently if the discussion forum is enabled the instructor/TA must create a category in order for students to post. We should create a default category to ensure that students can post immediately. It might also be nice to let the instructor know that they should create categories for the discussion forum.

Default categories: "General Questions", "Homework Help", "Quizzes/Tests". 
Course settings page create a link or display popup: "Customize the categories for the Discussion Forum"

**Comment by xprilion** [comment]
It might not be intuitive to display a pop-up on the settings screen for the forum categories, and would also call in for repeat code (since we already have a popup for category management in place, but it seems more understandable on the create thread page). 

I would say, on checking the Discussion Forum, a line slides down into view from there, prompting the user to ~setup~ manage the categories (this would not hamper the flow of the settings page as it has auto save on each change). 

@sak6lab @andrewaikens87 what do you think?

**Comment by xprilion** [comment]
@bmcutler @andrewaikens87 confirming, are we going for a popup on the same page or redirecting to the create thread > edit categories or creating a new page for editing categories?

**Comment by xprilion** [comment]
The `addNewCategory()` method currently does not accept any arguments. This makes it forced to work with the `$_REQUEST` variable. 

However, if it could accept arguments, it would be easier to reuse this function while solving this issue.  Shall I the function to accept the data passed to it as arguments? Or will @andrewaikens87 be doing it as part of the ForumController refactor? 

or should we completely pass on this and implement a different function altogether?

**Comment by sak6lab** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create default category for discussion forum](https://trello.com/c/XtduJQ8I/4-create-default-category-for-discussion-forum)

**Comment by sak6lab** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove attached images from discussion forum](https://trello.com/c/eCfMnCWC/5-remove-attached-images-from-discussion-forum)
