### ISSUE TITLE
Improve showing alerts/errors/etc to users

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#336]
Right now, the TA side of things does not have a good unified way to show these sorts of things to users and can lead to some confusion when something doesn't happen as expected. The submission side of things just shows a new "panel" on the page with any errors. I'd like to something that could be used throughout the system, such as bootstrap's alert dialogues. 

This screenshot shows what I mean (showing errors, notices, and successes dialogs):
![popup](https://cloud.githubusercontent.com/assets/1845314/14584692/47d231f8-0420-11e6-923c-463f8c57a8d6.png)

These would then be on the screen till either the user dismisses the alert, reloads the page, or goes to a different page.

Thoughts @bmcutler?

**Comment by bmcutler** [comment]
The current panel message system for submission (if we're talking about the same thing), goes mostly unnoticed by students.  Yes, switching to something more obvious (with color?) could/would be an improvement.  These messages are overlaid on the normal page text?  Sounds good, but I'd like to see exactly what they look like.

**Comment by MasterOdin** [comment]
Here's a more pulled back screenshot of these alerts on the page. 

![screenshot 2016-04-16 23 17 45](https://cloud.githubusercontent.com/assets/1845314/14584840/824067f2-0429-11e6-8dfd-7f7aa8fb7e10.png)

**Comment by bmcutler** [comment]
Overall it looks good.  

I just have questions about the UI.  I don't know what is best (we need testing & feedback).  Using a standard package for these seems like a good plan.

We don't want to require annoying, unnecessary, or non obvious clicking to make these go away.  
I assume these are rare?  We need to have clear guidelines for when to use these.  
How do we make sure the user doesn't miss or ignore them? Sometimes its ok for a user to miss or ignore a message.  Sometimes we need to confirm that the user saw the message before letting them proceed.  Is that the same message interface?
Is the size fixed? (does not depend on how big the window is?)  What is the right size?
What happens when you scroll?  (Does the message scroll with the page contents or does it stay fixed within the browser window?)

**Comment by bmcutler** [comment]
Also, you show multiple, so that means we can have multiple popup at once?  
Can a user interact with a page without closing the popups?  
What if the page auto-refreshes?  (Like when the submission results finish.) Do additional popups appear over time?  Do the earlier ones disappear or do they stack up until you close them?

**Comment by MasterOdin** [comment]
Right now you have to click the "x" on the right side to dismiss the message. I would say additionally add a timeout of 5-10 seconds on each message to have it disappear. Well, perhaps only have timeout on notices and successes and force user to dismiss errors themselves.

I'm envisioning these mainly appearing after submitting a form. I've only have one form right now (Class Configuration) and they show up for:
1. Error (red) if class name is blank (form is not saved)
2. Notice (yellow) if you input a non-number for default late days (form is saved using [intval](http://php.net/manual/en/function.intval.php) on those fields)
3. Success (green) if update is successful 

Exceptions/Errors thrown in the system still have their own page.

Size of the alert is 40% of window size and grows/shrinks as you play with the window size. It looks fine to me when shrinking the window as small as possible (can show you this on Tuesday).

The user can still interact with the page, but not on elements that are underneath the message.

The messages only show up on that page. If you leave it (or refresh), the messages won't appear again. I don't think they should remain as you're no longer doing whatever action caused the message to appear in the first place and the user has chosen to ignore the message (if it wasn't dismissed).

**Comment by bmcutler** [comment]
It all comes down to when they are used.  
Do we really need the green ones?  Will it be annoying for the power user to get these every time data is entered correctly?  I've heard grumbling from some TAs that the blue animated bar for lab & test data entry is annoying.  (I tried to explain that the animation was visualizing the communication of an ajax call and they should be happy the data is transferring and be patient.)
Why is 10 seconds the right timeout?  If I blink and miss it, that's a problem.  Or if I want to file a bug report but the message disappears and I can't quote the exact text that's a problem.

**Comment by MasterOdin** [comment]
I wouldn't use these for labs/tests/other, but I believe we should have some form of indicator for ajax status. I would also give these a timeout of 5 seconds I think. It's long enough that you shouldn't be able to "blink and miss it" but I don't think there's help for the user who submits a form then immediately tabs away/closes the tab. Perhaps once we've got things further along on 1.0 we have some user trials on these to see how people react?

The messages should be short enough to remember the gist of it though which with a combination of what they're doing should be easy to track/debug.
