### ISSUE TITLE
Instructor Web UI for Creating a Course

### ISSUE THREAD

**Issue by prestoncarman** [Submitty/Submitty#3398]
The process for setting up a class is complicated and uses many steps at the command line. While the documentation explains each step, it would be nice to be able to use one interface for all tasks. I would like to be able to create a course and manage all aspects of the class through the web UI. 

Advantages:
- Lower server administration
- Simplified user experience
- Clean workflow

Features
- Create a new course
- Manage course details

Other featues could be incorporated with the goal of completely managing a course from the web UI.

**Comment by N-Perry** [comment]
I am interested in solving this issue!

**Comment by SujalAhrodia** [comment]
Although I agree with the solution of building a web GUI for setting up the class, however I am not sure if that can be done for every task of the application. 
Are you only focussing on the setting up phase right now?

**Comment by prestoncarman** [comment]
@SujalAhrodia What types of tasks do you think could not be managed through a web GUI.

While am a fan of having a web GUI, the biggest issue I have with the course creating is the number of steps. I recently created a class and had a typo in one of the commands. It took me an hour to realize the issue. Partly due to my lack of knowledge but also because the process is not that simple.

**Comment by MasterOdin** [comment]
It should be noted that any web UI would be built on-top of using the [submitty_daemon_jobs](https://github.com/Submitty/Submitty/tree/master/sbin/submitty_daemon_jobs) or submitty_cgi to actually execute the appropriate scripts within sbin via a well placed setuid to give submitty_daemon/submitty_cgi root priviledges on just that script (so it can then make/chown/chmod the appropriate folders.

@bmcutler, your thoughts on which would be more appropriate? It feels like we'd want to go with the latter (submitty_cgi) so that the actions can be carried out instantaneously instead of asynchronously (and potentially delayed if a bunch of instructors are doing a bunch of other tasks at the same time).

**Comment by SujalAhrodia** [comment]
@prestoncarman I share the love for web GUI as well. 
But as I was going through the structure, I guess the main reason of switching to a web GUI is to allow non-technical instructors perform these tasks. Although creating a class shouldn't be much tedious, I was curious to know how to handle the automated generation on test inputs? 
According to my understanding, they are supposed to define the set of rules for these inputs. So are they supposed to code the rules or is there any other way? 
Please correct me if I have got anything wrong here.

**Comment by prestoncarman** [comment]
@SujalAhrodia Your idea is a bit larger than I was considering. I was just thinking about the initial course creation, adding instructors, TAs and students. I was not thinking about how an individual would create a gradeable. It would be nice to have a simple way to include a library of preset up gradeables to choose from, but creating a new gradeable probably does require some sort of command line access.

**Comment by bmcutler** [comment]
We may want to re-introduce the concept of an 'admin' user (can't quickly find relevant issue right now).  Perhaps 'instructor' users cannot make courses or users on the system, but an admin user can.  (And on a small production installation with a small number of instructors, the instructor can be the higher priviledge admin user and do simple admin tasks from the website).  Or maybe this is just an API thing?

**Comment by zjxiaohan** [comment]
I am working on this issue and I am not sure if I am on the right direction. Here's the outline of how I'd like to implement an easier interface to course creation. Please let me know if there are things going wrong. @MasterOdin 

1. Only superuser or maybe including faculty (see https://github.com/Submitty/Submitty/pull/3987) are allowed to create a course.
2. They create courses by providing four things: semester, course title, head instructor and base course. The newly created course would "inherit" base course's user groups.
3. These config params are passed through the API endpoint (and a GUI in the future) and the underlying PHP code sets up a daemon task.
4. The daemon runs scripts needed (create course things and add head instructor to the course). Those scripts should be modified as set-uid (as creating directories require `sudo`) executables so that the daemon is able to run it.
