### ISSUE TITLE
Enable users to sort posts from newest to oldest in a thread

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#3409]
Currently, there are three ways to sort posts in a thread: hierarchical, chronological and alphabetical. Among them, chronological mode sorts all posts in a thread from oldest to newest.

However, there may be a scenario where the thread is very long and some users may want to know the latest updates. It would be tiring to scroll all the way down the page. Hence, it may be helpful if, instead of oldest to newest by default, there can be two chronological modes: ascending and descending.

**Comment by Sahil333** [comment]
Is it okay?
![Screenshot from 2019-03-17 20-53-58](https://user-images.githubusercontent.com/14136740/54489336-1b022180-48d1-11e9-9c69-b13ec63f8ff6.png)

**Comment by bmcutler** [comment]
This is a nice feature to add.  You can make a PR for this.  Thanks!

However, I think we need to delay merging this to the master branch until we have a redesign of the bar of buttons at the top of the forum.  With a narrow browser window, the buttons become crowded and things wrap poorly to a second line.  

We don't have a clear design of what the forum option bar should contain (also, we want to reposition & somehow highlight the search option, since many students currently can't find it!  and ask duplicate questions)

**Comment by bmcutler** [comment]
@andrewaikens87  any comments?

**Comment by zjxiaohan** [comment]
@bmcutler Indeed, I also consider it necessary to redesign the bar, not only because the buttons are crowded, but also that this is a thread-level thing, I would consider it more proper if forum-level buttons and thread-level buttons are separated. They are separated by colors now, which, appears not that clear to me. When I first saw it, I thought they are used to sort threads instead of posts in a single thread..

**Comment by Sahil333** [comment]
Indeed, the buttons are crowded. I was also thinking there should be a redesign of the Forum bar. We can replace the text buttons with icon buttons (with hover text). This will give us space for the search text box. With the search text box, students will be directly able to enter text rather than first clicking on a button with Search text.

**Comment by MasterOdin** [comment]
We could replace it with icons or do what GitHub does with their "Merge" button on PRs where it's the text of the action (Squash and Merge, etc.) and an arrow which if you click would show the other options. For this, we'd make the whole button clickable to bring up the other options and then selecting one changes to the appropriate view.

**Comment by Fenn-CS** [comment]
@bmcutler @MasterOdin  @Sahil333  What if the filter button is replaced with a dropdown menu with rest of the options falling as menu items over it?
