### ISSUE TITLE
Dimensions of ta grading workspace

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3412]
If a course has lots of additional sidebar items.  AND/OR, the dimensions of the browser window are small enough so that the sidebar is taller than the browser window, the ta grading default layout stretches to the height of the sidebar, rather than the height of the browser window.  This is problematic because some windows can be default placed off the bottom of the screen and are not visible at all.

Instead, the dimensions of the ta grading space should max to be the height of the browser.

This is similar to the challenge for the forum scrolling.  
@andrewaikens87 -- any comments/suggestions?

**Comment by xprilion** [comment]
Noticed the problem in the browser and found this issue already existing! Would like to solve it! :)

**Comment by drumilpatel2000** [comment]
For reference you can see 
![ezgif com-video-to-gif(16)](https://user-images.githubusercontent.com/42701709/55794271-73000280-5ae2-11e9-92ea-d9e1253acf4d.gif)
This problem is basically caused due to `col-md` and `col-md-auto` in `nav-body` and `sidebar` respectively
This problem exist in every page but only visible for which height of `nav-body` is smaller than sidebar

**Comment by bmcutler** [comment]
duplicate / related to #2734?

**Comment by DefinitiveAbove** [comment]
Looks like this issue is fixed with the new TA grading interface.
