### ISSUE TITLE
Oral Assignmets

### ISSUE THREAD

**Issue by mariam-beshary9** [Submitty/Submitty#3527]
What about adding a feature of submitting oral Assignments ? I suggest adding a feature of sending voice records and receives voice feedback in need  . (I do not have technologies to know how actually but i only guess so i can not work on that currently )
I think it would be a good feature for language courses :) It would let submitty be also a platform for voice communication between TA/Dr and students . I hope this suggestion be suitable and benefit you in long term.

**Comment by drumilpatel2000** [comment]
If @bmcutler wants this feature. It can be easily implemented using WebRTC as Assignment will take place online. We can also implement video Assignment using WebRTC

**Comment by bmcutler** [comment]
Thanks for the suggestion!  We do allow submission of basically any file type.  (Just limited by the total file size for the assignment and web server configuration).  So students can already submit audio and video files they record/prepare using their favorite software.

Most of our feature requests are driven by instructor or student need.  
When we have a specific course and/or instructor that will use such a feature, we can re-open the issue, but at this time, since I am unaware of a specific use case, I'm going to close the issue for now.
