### ISSUE TITLE
Bug after using close all button on grading interface

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#3584]
**Describe the bug**
When grading an assignment, if you open the testcases pane, and hit "Close All" and then "Expand All", the testcases are not shown.

**Expected behavior**
The testcases would be shown after hitting "Expand All"

**To Reproduce**
1. Go to grade student assignment
2. Open testcases pane
3. Hit "Close All"
4. Hit "Expand All"

**Additional context**
To actually show the testcases, you have to click the "Hide Details" link. It looks like the "Hide All" is not properly toggling the state of the variables there (as after hitting "Hide All", the link for each testcase still says "Hide Details" instead of "Show Details".

**Comment by xprilion** [comment]
The `Hide details` / `Show details` links (they are not links, just text dressed up like links)  are being controlled by `loadTestcaseOutput()` in `server.js`. 

The above function is called in the `openAllAutoGrading()` for each div. Which essentially makes the `Expand All` button more of a toggle button. For example - 
https://www.loom.com/share/ecb6e99c22204af5a8834b716fa6c9d9

Now there are two ways this situation could proceed - 
[1] Remove the Close All button, simply change the text of the "Expand All" button on click. This will cause any e2e tests using the Close All button to need modification.
[2] Change the 'Hide details' to 'Show details' by introducing a unique ID for their parent span and using that in the handler for the Close All button. 

I have the 2nd solution ready. While the 1st solution sounds easier and more intuitive (why display a Close all button when already details are hidden?) and also leads to shorter code, there's a scenario where it would fail - 

(Assuming the 1st solution is implemented - https://www.loom.com/share/95471ce526954212a0fec098f2129122)
1. Click on Expand all, all details are shown
2. Click on a single test case's (say No. 3) Hide details
3. Click on Close all (since the text has changed for the Expand all button)
4. All test cases would toggle, but No. 3 would show up.

Submitting 2nd solution in PR #3588 to fix this issue, however I would like review on whether the Expand All button should or should not function like a toggle button!

**Comment by MasterOdin** [comment]
I think we should go with the second suggestion (keep both buttons, and maintain what state the testcases are in and show/hide as appropriate depending on the button selected.
