### ISSUE TITLE
NPM to manage dependencies is broken

### ISSUE THREAD

**Issue by drumilpatel2000** [Submitty/Submitty#3639]
**Describe the bug**
After PR #3609 , Javascript libraries were not working properly and giving errors. 

**Expected behavior**
Javascript libraries should work as before 

**To Reproduce**
1. vagrant ssh `sudo /usr/local/submitty/.setup/INSTALL_SUBMITTY.sh;`
2. You can see errors on terminal
3. You can also see errors on website

**Configuration**
 - OS: All
 - Browser: All

**Screenshots**
Errors on `sudo /usr/local/submitty/.setup/INSTALL_SUBMITTY.sh;`
![Screenshot from 2019-05-03 11-22-51](https://user-images.githubusercontent.com/42701709/57121753-11f0e500-6d97-11e9-9a80-f2ccf7de9ec4.png)
![Screenshot from 2019-05-03 11-22-00](https://user-images.githubusercontent.com/42701709/57121754-12897b80-6d97-11e9-813b-6b14aab4f7e1.png)
Errors on website
![Screenshot from 2019-05-03 11-21-42](https://user-images.githubusercontent.com/42701709/57121755-12897b80-6d97-11e9-82d2-ad2e0dc61a45.png)

**Additional context**

**Comment by drumilpatel2000** [comment]
@MasterOdin , Please have a look at this is probably breaking change

**Comment by xprilion** [comment]
Facing the same issue, my /site/public/vendor is missing entirely!

**Comment by MasterOdin** [comment]
So the error here is that Node/NPM isn't being installed correctly within the migrator, which cascades to INSTALL_SUBMITTY.sh not working properly as it cannot install the stuff from the new package.json.

The underlying problem with the migrator is most likely that your VM has had its time drift (it looks like the hack I put in place years ago is no longer working well to correct that) which causes the `apt-get update` that happens in it to fail.

To confirm, run:
```
date
```
and it will most likely be off. To fix, run:
```
sudo service ntp stop
sudo ntpd -gq
sudo service ntp start
```

and then retry running the submitty_install.

**Comment by mattraneri** [comment]
I believe there were a few people who were having issues with the internet in their VMs during the installation process, so that's something to double check that your VM can do- I recommend opening the scripts, there's a file for npm installation that gets piped into bash, make sure you can curl that file from within the VM.

**Comment by pbailie** [comment]
This hit me in both Vagrant and my dev VM.  My dev VM's Internet connection is fine.

I see that `INSTALL_SUBMITTY_HELPER_SITE.sh` encounters these errors, mainly with bash command `cp`.
```
-su: npm: command not found
cp: cannot stat '/usr/local/submitty/site/node_modules/@fortawesome/fontawesome-free/css/all.min.css': No such file or directory
cp: cannot stat '/usr/local/submitty/site/node_modules/@fortawesome/fontawesome-free/webfonts/': No such file or directory
cp: cannot stat '/usr/local/submitty/site/node_modules/bootstrap/dist/': No such file or directory
cp: cannot stat '/usr/local/submitty/site/node_modules/chosen-js': No such file or directory
cp: cannot stat '/usr/local/submitty/site/node_modules/codemirror/lib/codemirror.js': No such file or directory
cp: cannot stat '/usr/local/submitty/site/node_modules/codemirror/lib/codemirror.css': No such file or directory
cp: cannot stat '/usr/local/submitty/site/node_modules/codemirror/mode/': No such file or directory
cp: cannot stat '/usr/local/submitty/site/node_modules/codemirror/theme/monokai.css': No such file or directory
cp: cannot stat '/usr/local/submitty/site/node_modules/codemirror/theme/eclipse.css': No such file or directory
cp: cannot stat '/usr/local/submitty/site/node_modules/flatpickr/dist/*': No such file or directory
cp: cannot stat '/usr/local/submitty/site/node_modules/jquery/dist/jquery.min.*': No such file or directory
cp: cannot stat '/usr/local/submitty/site/node_modules/jquery.are-you-sure/jquery.are-you-sure.js': No such file or directory
cp: cannot stat '/usr/local/submitty/site/node_modules/jquery-ui-dist/*.min.*': No such file or directory
cp: cannot stat '/usr/local/submitty/site/node_modules/jquery-ui-dist/images': No such file or directory
cp: cannot stat '/usr/local/submitty/site/node_modules/jquery-ui-timepicker-addon/dist/*.min.*': No such file or directory
cp: cannot stat '/usr/local/submitty/site/node_modules/pdfjs-dist/build/pdf.min.js': No such file or directory
cp: cannot stat '/usr/local/submitty/site/node_modules/pdfjs-dist/build/pdf.worker.min.js': No such file or directory
cp: cannot stat '/usr/local/submitty/site/node_modules/pdfjs-dist/web/pdf_viewer.css': No such file or directory
cp: cannot stat '/usr/local/submitty/site/node_modules/pdfjs-dist/web/pdf_viewer.js': No such file or directory
cp: cannot stat '/usr/local/submitty/site/node_modules/twig/twig.min.js': No such file or directory
```
So a bunch of files are not being copied.  Some of those files are used by `Output::addVendorCss()` and `Output::addVendorJs()`, but since they didn't get copied, `filemtime()` triggers the warning, while some CSS and JS code goes missing.

Interestingly, looking at first line of the error log, `-su: npm: command not found` — I can do `$ npm --version`  and I get `6.9.0` in response.  So, npm appears to be available.

**Comment by MasterOdin** [comment]
what are the permissions on npm?

**Comment by xprilion** [comment]
After my last comment in here I suffered from bad internet connection for a day. Later, got a good connection but had some other issues.

Finally, a completely clean installation (in which I used the latest box image for Ubuntu 18.04) worked and I get no more errors.

**Comment by pbailie** [comment]
npm appears to be owned by my login account despite that I am always working in my dev VM as root.

**Comment by MasterOdin** [comment]
How did you install npm and did you independently update it?

**Comment by linhbngo** [comment]
I ran into the same issue. I don't remember how/why npm was installed, but the symbolic link inside /usr/bin/ points to a relative path:

root@submitty:/usr/local/submitty/GIT_CHECKOUT/Submitty# ll /usr/bin/npm
lrwxrwxrwx 1 root root 38 May  6 15:20 /usr/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js*
root@submitty:/usr/local/submitty/GIT_CHECKOUT/Submitty#

**Comment by MasterOdin** [comment]
That's fine and how npm gets installed (and any globally installed package that has commands, though I believe they're placed in /usr/local/bin instead of /usr/bin).

**Comment by linhbngo** [comment]
For me, the issue seems to be that submitty_php cannot invoke npm (even though it is installed in the system) on line 61, INSTALL_SUBMITTY_HELPER_SITE.sh

Backtracking, I found that the ../lib/node_modules/npm/bin/npm-cli.js* location I found in a previous post is set to 750 inside npm/bin. After chmod -R 755, submitty_php was able to invoke npm. 

When rerunning install_system.sh, the issue happens again. It turns out that npm install -g npm (line 214, install_system.sh) reset the npm directory to 750 again. I manually ran that line, then chmod -R 755, then comment it out and rerun install_system.sh. This makes the issue goes away.

**Comment by pbailie** [comment]
In my testing, I conclude that the underlying cause is Submitty's default umask of 0027.

Updating npm (`npm install -g npm`) will set npm's permissions to `rwxr-x---` (consistent with umask of 0027) , and submitty_php can't execute npm.  But if you set the umask back to Ubuntu's default of 0002, and then update npm, the permissions are `rwxrwxr-x` (consistent with umask of 0002) and submitty_php can execute npm.

Further consideration: umask gets set by `install_system.sh` starting on line 241, which comes after the npm update command on line 216.  This means a fresh install of Submitty won't have any permissions problems (which is why `vagrant destroy/up` works OK).  But since umask 0027 is made default during the first time Submitty is installed, using `install_system.sh` to _migrate an existing system_ for using npm will set npm's permissions to be inaccessible by `submitty_php`.  Which then leads to the error as described.

The quick and easy fix is ensure umask is set to permit world read and execute prior to running
 `npm install -g npm`.

**Comment by bmcutler** [comment]
On our production box, when I tried manually running the steps above, I got this error:

E: Repository 'http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease' changed its 'Label' value from 'Oracle Java (JDK) 8 Installer PPA' to 'Oracle Java (JDK) 8 Installer PPA (DISCONTINUED)'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.

So I followed the instructions on this site to fix Oracle Java 8 repository:
https://forums.linuxmint.com/viewtopic.php?t=279928

Then re-ran the installer and it looks ok...

**Comment by bmcutler** [comment]
PR #3689 should fix this issue..  if npm is working on an existing install, and we re-run install_system.sh on that existing install it should not break npm.

If you have a broken npm:  

@MasterOdin will please post a followup and insert the instructions for how to manually fix this problem in this issue (so if someone searches they will find this discussion)
and then close this issue.

Thanks!

**Comment by MasterOdin** [comment]
As @pbailie mentions above, when installing packages with npm globally (or using pip for that matter), you need to make sure you run it after setting your umask for that shell back to the default so that G+O have read/execute access (e.g. `umask 0022` or `umask 0002`), or by just spawning a new shell (briefly) by doing: `(umask 0022 && npm install -g npm)`.

If you've done `npm install -g npm` without first setting your umask, the installation will succeed, but the permissions will be such that only the owner (root) can do anything and all other users will report the command doesn't exist. To fix this, the best bet is to do (as root):
```
npm install -g npm@6.4.0
npm install -g npm
```

to rollback npm to an older version and then re-installing the newest version. This will cause it to self-fix all of the permissions of the files that it installs and requires. For other globally installed packages, it's probably easier to just uninstall and then re-install.
