### ISSUE TITLE
Nightly run of "Generate Grade Summaries" and Rainbow Grades

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3711]
**What problem are you trying to solve with Submitty**
Currently, Generate Grade Summaries only happens when the instructor presses the website button.  And Rainbow Grades happens on the instructors local machine (copying files on & off, running C++ code).

We'd like to have this done once per day by a cron job run by submitty_daemon.

**Describe the way you'd like to solve this problem**
submitty_daemon can't press the generate grade summaries button.  And we don't want to port the php code to python.  But this is the right place to do an API call, right?  Maybe?
Generate grade summaries saves files to the server, then the submitty_daemon job takes over easily.

**Comment by Kevin-MM** [comment]
@bmcutler What is the status of this?  I had considered porting the code that generates grade summaries to a python script so in that manner the script can either be triggered from the web gui or from another python script.  A second more complex Python script would handle automating all the other rainbow grades steps as described on submitty.org.

**Comment by holzbh** [comment]
@Kevin-MM I'm against porting the code because it ties into the database quite a bit and every time we change a model we'd need to change this python script, and it'd be a lot of replicated code across PHP and Python. 

At least at RPI we have a `submitty-admin` user that has access to all courses through the website, and ideally whatever script you write would either "log in", go to the right course, click generate grade summaries, and wait until the procedure was done OR if we have an API, it would use the API to do this process.

The rest of the code using a secondary script is fine - you should be able to adapt most of the [https://github.com/Submitty/Submitty/blob/master/tests/rainbowGrades/test_sample.py](Rainbow Grades test script) as a starting point.

**Comment by bmcutler** [comment]
Re-opening, closed prematurely, still need to automate a few more pieces

**Comment by zjxiaohan** [comment]
Is this closed by https://github.com/Submitty/Submitty/commit/cd88429f9fc85fed9fca5b61ca8fcd6e864d5c4c ?

**Comment by Kevin-MM** [comment]
No, we've handled triggering the process from a button click on the UI, but we are working on having a cron job type system in place that runs rainbow grades for all enabled courses nightly.  Once that is done this issue will be resolved.
