### ISSUE TITLE
Overhaul Notebook Contents

### ISSUE THREAD

**Issue by emaicus** [Submitty/Submitty#3728]
## Issue
The structure of a notebook object is currently more rigid than it could be, restricting where and how instructors can interleave descriptive text and images and student input.

## Proposed Design
At present, each sub-component of a notebook can contain multiple inputs. Instead, we will consider each sub-component to be a piece of information to be displayed to the user, be it a type of input (e.g. a short answer question) or a type of output (e.g. formatted markdown text). This will allow instructors greater flexibility when deciding in which order inputs and outputs are displayed to their students.

We will support the following sub-component types:
1.  __Short Answer Input:__ Short answer sub-components  will represent both codeboxes and textboxes, and will contain the following fields:
    * ```filename```: The file to which input will be saved.
    * ```starting_value```: ___Optional___ A value to be pre-populated into the short answer box.
    * ```programming_language```: ___Optional___ If specified, CodeMirror is used to display the input box.
    * ```rows```: ___Optional___ The height of the input area in rows.
2.  __Multiple Choice Input:__ Multiple choice sub-components will allow the following fields:
    * ```filename```: The file to which input will be saved.
    * ```choices```: An object which maps a key to an option (e.g. ```{"a" : "Apple", "b": "Banana"}```)
    * ```allow_multiple```: specifies whether multiple options can be selected.
3.  __Markdown__: A piece of markdown to be displayed to the user. This sub-component type must have exactly one of the following fields:
    * ```markdown_string```: A string of markdown embedded directly into the ```config.json```.
    * ```markdown_file```: A markdown file to be displayed to the student.
4. __Image__: An image to be displayed to the user. Images can have the following fields:
    * ```image```: The image file to be displayed.
    * ```height```: ___Optional___ The height at which the image is to be displayed.
    * ```width```: ___Optional___ The width at which the image is to be displayed.
    * ```alt_text``` ___Optional___ Alt-text to be displayed to screen readers.

**Comment by bmcutler** [comment]
In the PR to tackle this issue @Kevin-MM please address @MasterOdin 's about the foreach (if still relevant) in #3719.

**Comment by MasterOdin** [comment]
It should be noted, that we probably want to look into moving the code also to a more object-oriented design as opposed to the associative array structure it currently has to make it easier to also understand the elements of a notebook, testing it, adding defaults for things (like `alt_text`), etc.

**Comment by bmcutler** [comment]
A few notes:  

instead of 'subcomponent', can we just call these things cells of a notebook?  (component is overused in other parts of the system)

how about "initial_value" or "initial_string" instead of "starting_value"

I think "choices" should be an array so order is preserved.  Otherwise it will alphabetize by key which won't always be as desired e.g.:  "false", "true"  or  "medium", "short", "tall".  (yes, unfortunately makes it bulkier)

I hope markdown can be either just a string, or an object with the field "markdown_string" or "markdown_file"

If we want to put multiple images in a horizontal row (the current example has that), can we just do multiple image cells in a row and they will pack horizontally if they fit?  And the next non-image cell will start a newline?    (I'm also ok not allowing the formatting of multiple images horizontally in version 1 of this rewrite, it's not at all important.  If it doesn't happen easily just skip it until we have an actual use case.)

**Comment by Kevin-MM** [comment]
Could you please give a code example of how the key value pairs will be organized when packaging ```choices``` into an array?

**Comment by bmcutler** [comment]
It's bulky, but this is what I suggest for the expanded version:
{
   "choices" : [ 
       {"value": "short", "description": "the plant will be short because it doesn't get enough water"}, 
       {"value": "medium", "description": "the plant will grow normally"}, 
       {"value": "tall", "description": "the plant will be tall because it gets lots of light"} 
   ],
  "filename": ...

}

Value is what gets saved to the filename.
We could make some rewrite rules (in later PR!) to allow instructors to write:
{
"choices" : [ "true", "false" ],
...
}

Which can expand to objects with descriptions that are empty string.

**Comment by bmcutler** [comment]
Could also have the more traditional choice 'value's: 
"choices" : [
{"value": "a", "description": "the plant will be short because it doesn't get enough water"},
{"value": "b", "description": "the plant will grow normally"},
{"value": "c", "description": "the plant will be tall because it gets lots of light"}
],

**Comment by Kevin-MM** [comment]
I wonder if it wouldn't be better to use more common conventions like

```
"choices" : [
    {"key": "a", "value": "the plant will be short because it doesn't get enough water"},
    {"key": "b", "value": "the plant will grow normally"},
    {"key": "c", "value": "the plant will be tall because it gets lots of light"}
]
```

**Comment by MasterOdin** [comment]
@bmcutler's example is right and what we want to use as the choices aren't true key/value pairs as the instructor should only write tests that deal with the value while the description is just there to show to the student for informational purposes.
