### ISSUE TITLE
Test case for to confirm we catch zip bomb & proper error message

### ISSUE THREAD

**Issue by djsamseng** [Submitty/Submitty#38]
- [ ] A zip bomb should first be tested in a non production, full installation server.

Then we should create automated tests of:
- [ ] zip file size > allowed
- [ ] uncompressed size of files (according to "table of contents", e.g. "unzip -l" ) > allowed
- [ ] zip bomb (uncompressed size of files appears smaller than it really will be), actual uncompressed size >> allowed

https://en.wikipedia.org/wiki/Zip_bomb

**Comment by bmcutler** [comment]
- [ ] A zip bomb should first be tested in a non production, full installation server.

Then we should create automated tests of:
  - [ ] zip file size > allowed
  - [ ] uncompressed size of files (according to "table of contents", e.g. "unzip -l" ) > allowed
  - [ ] zip bomb (uncompressed size of files appears smaller than it really will be), actual uncompressed size >> allowed

https://en.wikipedia.org/wiki/Zip_bomb

**Comment by jungj5** [comment]
I'll try to help out with implementing this

**Comment by Mijumaru3** [comment]
I can try to help out also.

**Comment by jungj5** [comment]
I am trying to implement a simple for loop that'll check if any of the files inside of the submitted zip folder is also zip folder but it doesn't seem to work. Not sure what's wrong. Would anyone like to look into it? I feel my lack of php knowledge is what's causing the problem.

**Comment by MasterOdin** [comment]
Check in the code to a branch or email me it.

**Comment by jungj5** [comment]
Pushed it onto the testing branch. Code compiles but doesn't seem to do anything. I tested it by uploading a zip folder with a zip folder in it but nothing happened. Maybe the "filetype" function doesn't do what I think it does.

**Comment by MasterOdin** [comment]
so here's a quick output of what your code does:
```
Array ( [name] => test.zip [type] => application/zip [tmp_name] => /tmp/phpHhAiXG [error] => 0 [size] => 498 ) 

test.zip -- 
Warning: filetype(): Lstat failed for test.zip in /usr/local/hss/website/public/controller/data_functions.php on line 158

application/zip -- 
Warning: filetype(): Lstat failed for application/zip in /usr/local/hss/website/public/controller/data_functions.php on line 158
/tmp/phpHhAiXG -- file

0 -- 
Warning: filetype(): Lstat failed for 0 in /usr/local/hss/website/public/controller/data_functions.php on line 158

498 -- 
Warning: filetype(): Lstat failed for 498 in /usr/local/hss/website/public/controller/data_functions.php on line 158
```
(this is print_r($filename) and print on $file)

So this shows two issues:
1) You're only looking at the submitted file (which will always be a zip). You want to move this down to when the zip->extractTo function to do this (if at all?)
2) [filetype](http://php.net/manual/en/function.filetype.php) does not return file extensions, but rather if something is a file, dir, symlink, etc. You want to use [pathinfo](http://php.net/manual/en/function.pathinfo.php) to actually get this information.

Granted, I'm not sure the full scope of this issue, but does a zip bomb currently affect the server (and thus necessitates code change) or does not? @bmcutler?

**Comment by jungj5** [comment]
It would appear that the code I posted just now catches the zip directories within the hw submissions but never returns an error message for the student to know. The server will just keep trying to grade it. I know this because I submitted a lab assignment with a zip file and then submitted it without one. Any recommendations on how I can make the server stop grading and actually display an error message?

**Comment by MasterOdin** [comment]
Your code does prevent the assignment from being graded (it's never added to the queue), the problem here is that you don't clean up the created folder in submissions for the student on failure. So, after three bad submissions, I'll be left with:
```
pythontest
-- developer
   -- 1
   -- 2
   -- 3
```
in the submissions folder with no content ever being generated to results. You need to make sure you clean up that folder.
 
You should also be checking the files inside of the zip before extracting. The [ZipArchive](http://php.net/manual/en/class.ziparchive.php) object gives us some nice functions to accomplish this. Thus, we get:
```
for ($i = 0; $i < $zip->numFiles; $i++) {
    $stat = $zip->statIndex($i);
    $info = pathinfo($stat['name']);
    if (isset($info['extension']) && $info['extension'] == "zip") {
        rmdir($version_path);
        return array("error"=>"", "message"=> "Your submission contains a zip folder within the submission. Please remove it.");
    }
}
```
and put this above the ```$zip->extractTo(...)``` line. The reason to do this is that [rmdir](http://php.net/manual/en/function.rmdir.php) only works on empty directories and no need to insert recursive delete if we don't have to.

The error message is very not obvious though which is something that should get changed (is there an issue for it?)
![error](http://i.imgur.com/QWPtE6a.png) 
shows my quick attempt at it (different message).

**Comment by jungj5** [comment]
I implemented some code that would check what the uncompressed size of the student submission would be without extracting it. I was wondering what we should set the limit to for this? I currently have it so the website would return an error if the submission's uncompressed size was greater than 100mb. Should I change this?

**Comment by MasterOdin** [comment]
Right now, we do not check for the size of the zip, just that the contents of the zip are not too big. We shouldn't really have a case where the zip is "too big" but the files inside are not unless you are zipping a very small file (<100 bytes) where you're just getting the overhead of the zip.

Thoughts @bmcutler?
