### ISSUE TITLE
Cannot make new posts on Forum as Student

### ISSUE THREAD

**Issue by shailpatels** [Submitty/Submitty#3839]
**Describe the bug**
Students cannot select category buttons when creating a new post on the submitty forum.

At least one category should be selected but this prevents from anything getting selected which makes making posts impossible

**To Reproduce**
1. Log in as a student
2. Go to forum
3. Press "Create New Thread"
4. Try to select category
5. See error

**Configuration**
 - OS: Debian 9 (on vagrant)
 - Browser Firefox

Screenshots
![Screenshot from 2019-06-12 18-25-57](https://user-images.githubusercontent.com/12129065/59390563-b0317c80-8d3f-11e9-8e26-a7f89891d128.png)

For some reason instructors and TA's can make posts fine.

**Comment by andrewaikens87** [comment]
@shailpatels @xprilion @bmcutler I do see this on live as well (not sure where/when this broke, It seemed to work fine when I was reviewing). That button format is only supposed to display if the user doesn't have JavaScript enabled (this was done in GSOC '18). I can investigate tomorrow after work. I do believe that this should be fixed as soon as possible but the buttons do still work for me (although I admit this may not be intuitive). In order to check/uncheck the box you must directly click the box, not the button.

**Comment by shailpatels** [comment]
closed by #3841
