### ISSUE TITLE
Error If A Grader has Access to A Team's Rotating Section but not that of its Members

### ISSUE THREAD

**Issue by emaicus** [Submitty/Submitty#3846]
If a grader has access to a team's rotating section but not that of the individual members, the the team is not properly displayed on the details page. Instead, the team is decomposed into the individual members that the grader has access to, and each are displayed as having no team.

To reproduce, set a team gradeable to be grade by rotating section, and give a limited access grader access only to a subset of the sections. As an instructor user, navigate to the details page for the gradeable, and click the new "re-assign rotating sections" button. As the limited access grader, go to the details page for an assignment, and find a team that has been improperly displayed.

**Comment by jmcknight98** [comment]
I have looked into this and found that the issue seems to be slightly different than it was described here.  When "View Your Sections" is selected (limited access graders are always on this page), any team that is not in a rotating section currently displayed is decomposed, and its members are placed into their rotating section with "No Team" as described.
