### ISSUE TITLE
Add basic git testing to Travis to exercise apache configuration

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#3997]
Add testing of Git (basic endpoints) to Travis to ensure that we don't break the basic setup of making a repos, checking them out, pushing to them, etc.

This should follow from work done for #1040 to make Travis act more like production in general.

**Comment by zjxiaohan** [comment]
*Citing this because it may be useful.*

It does not get tested under Travis. Something that should probably be done first is making the Travis apache configuration more closely match the one running under Vagrant and then add some simple "e2e" test, doing something like:
```
git clone <repo_url>
cd repo
touch test.txt
git add .
git commit -m "Test"
git push
touch test2.txt
git add .
git commit -m "Second commit"
git push
git reset --hard HEAD~1
git pull
```

and just verify that none of the commands fail, and the resulting repo has the two empty files.

_Originally posted by @MasterOdin in https://github.com/Submitty/Submitty/pull/3864#issuecomment-502750279_

**Comment by zjxiaohan** [comment]
Do we need an API endpoint to enable the tester to create a gradeable that allows vcs submission and then do the test or it could possibly be done following `check_everything.py`'s fashion without doing modifications elsewhere?

**Comment by MasterOdin** [comment]
In the future yes, but for this, it's not necessary. I'm just making sure that the apache stuff works as expected (which also means that authentication.py and a specific path of vcs_login all work as expected) as we've had a few unintentional breaks that just a basic level of testing would catch and help prevent going forward.
