### ISSUE TITLE
[VPAT] Redundant Link in Breadcrumbs

### ISSUE THREAD

**Issue by pbailie** [Submitty/Submitty#4075]
I am seeing WAVE report a redundant link in the breadcrumbs.  See screenshot:
![Screen Shot 2019-07-12 at 6 32 16 PM](https://user-images.githubusercontent.com/12703624/61164502-bc962a00-a4e3-11e9-84dd-77ce5ba2c0d7.png)

What this is saying is WAVE has detected multiple links associated with the breadcrumbs (presumably attached specifically to "Submitty") that point to the same URL.  This may cause some screen readers to unnecessarily stop on the "Submitty" breadcrumb multiple times.

**Comment by mktung** [comment]
That's triggering based on the "home button" that appears on the mobile layout. We use `display: none` on one element while the other is shown. I thought `display: none` removed elements from the DOM, but WAVE is picking it up anyway. It seems the only way to avoid this would be to write JS to inject and remove large amounts of HTML, which we've been trying to avoid with TWIG. How should I handle this?

**Comment by elihschiff** [comment]
My bad merge request #4856 was for a different issue and does not solve this issue.

**Comment by elihschiff** [comment]
This looks like it is only an issue when you are working in a vagrant VM. If you run wave on the live version of Submitty, it does now have this issue. The live version has a link to the rpi computer science page (see image below) before the link to Submitty which therefore stops this from being an issue. Because this issue is only on development machines and is not a problem on production does it still need to be fixed just for development?

Production breadcrumbs:
![image](https://user-images.githubusercontent.com/18558130/73992342-d7ffd100-491c-11ea-8d8e-7bd1800d6506.png)

Vagrant (there is no link before the first "submitty" leading to the problem on vagrant)
![image](https://user-images.githubusercontent.com/18558130/73992391-ff569e00-491c-11ea-8455-54d295179b36.png)

**Comment by pbailie** [comment]
@elihschiff 

I develop using a VM server that I built and maintain from scratch, so that it is a closer experience to a real production server.  And the issue has always shown up in my VM (meaning this is not isolated to Vagrant).

![Screenshot](https://user-images.githubusercontent.com/12703624/74057515-17c4c800-49b2-11ea-82b1-b9af372ae615.png)

But as you note in Vagrant, there is no institutional homepage link (or any institution at all).  My VM does have an institution ("Labstaff"), but there is no configured homepage.  So, I added an institutional homepage to `config/submitty.json`, and the redundant link alert went away.  This implies that link code for an institution's homepage is getting attached to the Submitty homepage breadcrumb, when the institution's homepage isn't defined in the configuration.

That said, this does need to be fixed as this can conceivably appear in production for someone/somewhere.  But it is a very good clue as to what and where to look in the code.

Thank you for the help!
