### ISSUE TITLE
Give TAs download option for submitted files (and generated files from autograding?)

### ISSUE THREAD

**Issue by gonsie** [Submitty/Submitty#409]

**Comment by bmcutler** [comment]
This may still be happening

**Comment by ZishanHuang** [comment]
Tested doc, docx, xls, 7z, rar, working fine.

**Comment by bmcutler** [comment]
Maybe the issue was that the instructor/TA didn't know how to view the file.  What happens in the grading page for a submitted .docx?  I assume making an inline webpage viewer is not easy.  But instead we could implement a download file option.  Only enable that for the ta grading page though.  (Allowing students to download previously uploaded files should still be disabled by default -- until we have further design discussions).

**Comment by MasterOdin** [comment]
The webviewer definitely fails while trying to view docx. We should I guess implement it such that if the webviewer fails to recognize the content type, it just prompts the user to download the file.

**Comment by bmcutler** [comment]
more detail in related/duplicate issue #371
