### ISSUE TITLE
No scrollbar on TA grading interface

### ISSUE THREAD

**Issue by Kevin-MM** [Submitty/Submitty#4194]
**Describe the bug**
No scroll bar on the TA grading interface (see image below).

**Expected behavior**
If the navigation bar is greater than the height of the window, you should be able to scroll down to elements on the bottom of the navigation bar

**To Reproduce**
1. Log in as instructor
2. Enter the sample course
3. Click Gradeables
4. Grade the 'Grading Homework'
5. Click 'Index of Grading Details...'
6. Click any of the 'Grade' buttons
7. If the height of the navigation bar is not greater than the height of the window, zoom your browser until it is.
8. Observe that there is no scroll bar, and you can no longer access the bottom part of the navigation bar.

**Configuration**
 - OS: Ubuntu 18.04
 - Browser Chrome

**Screenshots**
![lost_scroll_bar](https://user-images.githubusercontent.com/7605020/61874727-21c02700-aeb7-11e9-97a3-b99dcc59c055.png)

**Comment by bmcutler** [comment]
Something has changed, but it's not that we want to add a scrollbar to the whole screen including the panels.  

The side bar should be able to move up & down (and the breadcrumb can moves off the top of the screen).

The forum has a similar problem.  Please see how it works right now (it hasn't changed).

Also tagging @andrewaikens87 because maybe he can explain what the ta grading page used to do when the side bar is taller than the page.

**Comment by mukul-kmr-jha** [comment]
I think It can be closed, thanks!
