### ISSUE TITLE
Documentation for preferred names & password

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4223]
Under the student pages, let's add a bit more to the login page with a section (with images) about how you can edit your preferred first & last name.

And also mention that if your system uses database password specific to this server, users can change their password through this UI.  (Hmm.. I thought the vagrant setup used database passwords, maybe I'm wrong?)

Also, let's document the home screen here where you can select a course from those you have access to.

**Comment by MasterOdin** [comment]
Vagrant sets up both PAM and database authentication for all users so that they can be easily switched between for testing purposes. Can either run CONFIGURE_SUBMITTY.py or just edit `/usr/local/submitty/config/database.json` and change the authentication method to `DatabaseAuthentication` to do it.

**Comment by bmcutler** [comment]
closed in 
https://github.com/Submitty/submitty.github.io/commit/eb2f9fc480cd7c5184751f2508e93a23a39b3b76
