### ISSUE TITLE
Display maximum number of files that can be uploaded to user

### ISSUE THREAD

**Issue by shailpatels** [Submitty/Submitty#4456]
**What problem are you trying to solve with Submitty**
Right now across submitty's file upload drag and drop areas users can add as many files as they want even the the max_file_uploads is restricted to 20 by php (by default).

**Describe the way you'd like to solve this problem**
On every interface to upload files display the max allowed to users and then do a client side check to prevent users from adding 20+. Since php already handles checking for a number of file.

**Comment by MasterOdin** [comment]
Let's either modify this issue or create a second to have the drag-and-drop.js incorporate this limit and not allow the user to add more files past it so that an instructor is better informed what's going on. I imagine that if they try and upload a file past the limit, a popup or something would appear briefly telling them it failed to add all files.

**Comment by shailpatels** [comment]
Ok I think a client side limit would helpful to incase the error fails. A lot of the site that check fails silently or a confusing/wrong error message is sent back to the user. Like forum textareas stop letting you enter text after the limit if something like that exists for uploading files that would good to add in my opinion.

**Comment by marwanatef2** [comment]
I'm working on this issue.
