### ISSUE TITLE
Add ability to order threads in different ways

### ISSUE THREAD

**Issue by BenKelly99** [Submitty/Submitty#4508]
**Describe the bug**
In the forum, the "reverse-time" search method (Chronological \\/) does not change the order in which the threads are displayed

**Expected behavior**
It should sort the posts from oldest to newest, perhaps with recent announcements at the top.

**To Reproduce**
1. Go a forum with some posts
2. Rank them by "reverse-time"/Chronological \\/
3. See error

**Configuration**
 - OS: Windows
 - Browser: Chrome

**Comment by elihschiff** [comment]
It looks like the different ways of sorting only apply to comments within a thread not the list of threads on the left. I tested and the modes seem to be working fine for the comments. 

However I do think it would be helpful to add a second sort button that is for the list of threads on the left as they are always sorted by post date as far as I can tell.

**Comment by AngadSethi** [comment]
Hello!

I am working on this issue. I'm adding options to sort the threads by _alphabetical order of thread titles_, _chronological ascending_, _chronological descending_ and by _thread IDs_. Is there any other option that I should incorporate?

Also, is it fine if I modify the function `getSortedThreads()` at `site/app/controllers/forum/ForumController2.php ` to get the job done?

A side note : I think the bug label should be removed since it really isn't a bug. The sorting function works perfectly in the posts section

Regards
Angad

**Comment by AngadSethi** [comment]
Hello!

Linked a pull request. Please review.

Regards
Angad Sethi

**Comment by bmcutler** [comment]
Closing this issue request because it is low priority and unlikely to be highly used.  

The UI already contains other ways to sort that are rarely used (but used by power users w/ teaching staff access for specific grading needs).

The issue stems from a confusion about what the current chrono sort feature does (it only sorts posts within a thread, never the threads).  We will be tweaking the visual/text to make the existing functionality more clear.

See also #9375
