### ISSUE TITLE
Calendar File Links Open in Existing Tabs

### ISSUE THREAD

**Issue by bnidevs** [Submitty/Submitty#4526]
Calendar file links open in existing tab instead of new tabs.

Opening files in new tabs will help students keep their browser organized and they can access other files on the calendar with the Submitty tab.

You can add `target = "_blank"` to calendar links if they're `<a>` tags or similar.

**Comment by bmcutler** [comment]
Thanks for your feedback, but I'm closing this issue because:
1) The DS calendar is not part of Submitty.  (it visually looks the same, but it's a separate site)
2) it can be argued that forcing it to open in a new tab is bad practice:
https://css-tricks.com/use-target_blank/
https://medium.com/the-metric/links-should-open-in-the-same-window-447da3ae59ba
