### ISSUE TITLE
TA Grading badge missing for penalty component

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4631]
**Describe the bug**
When a TA graded component is negative, the badge is missing

(Not sure if it matters if the component is penalty-only, or just if the total score is < 0 for a mark that allows penaltys and positive total)

<img width="164" alt="Screen Shot 2019-10-16 at 10 36 35 AM" src="https://user-images.githubusercontent.com/5871417/66929441-01f55680-f001-11e9-8827-6b3b2b904494.png">

**Comment by shreygupta2809** [comment]
I would like to work on this issue. Could you please guide me to the necessary section of the code base as this my first contribution in the organisation and I am not yet familiar with the code base. Thanks

**Comment by RaylockLLC** [comment]
Is anyone working on this issue or can I take it?

**Comment by eddiekrystowski** [comment]
@bmcutler It seems like this is just an issue when the point total on any component is 0. For example, in the following screenshot
![image](https://user-images.githubusercontent.com/28243927/121565368-64774380-c9ea-11eb-8441-a578880b3b44.png)
Both "Evil Component" and "Kind of Extra Credit" will not have badges. I assume this was only noticed with components with only penalty points since the correct way to give extra credit is to use the Extra Credit option on the rubric, which automatically gets a badge shown, not how I did here where I just had a mark (doesn't actually give extra credit).

So my question is, along with the badge being shown for components with only penalty points, should a badge be shown for components whose total point value is 0, but still have marks, like "Kind of Extra Credit" ?
![image](https://user-images.githubusercontent.com/28243927/121566770-d4d29480-c9eb-11eb-96bf-6a82c547fbe8.png)
Obviously this kind of component won't ever give any points, but should we give it a badge anyways so it is explicit?

Which leads to my other question, is there ever a case where we don't want a badge?
