### ISSUE TITLE
Fix Failing Forum Merge Thread Test

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4683]
Commented out in PR #4682

**Comment by MasterOdin** [comment]
While this is fixed in #4688, I'd like to use this issue as a "retrospective" of what happened an why disabling the test was deemed to be the appropriate course of action. Given that I was not at the Hackathon or related events on Saturday and Sunday, I can only put what happened from a perspective of the Git and Travis log:

1. I merged #4674 at 9:17am (outlaw the `and` and `or` logical operators) as part of my overarching goal of enforcing style. All travis tests were passing in the PR.
1. #4568 was merged at 1:52pm that re-introduced above logical operators, thus causing Travis to consistently fail on master (and anything that got master merged in) going forward. All travis tests were passing in the PR.
1. #4666 was merged at 2:06pm. Travis never passed any commit in the PR (due to it breaking forum e2e test).
1. #4676 was merged at 5:18pm, fixing lint test failures introduced in #4568, but E2E test still broken from #4666.
1. #4682 was merged at 12:50am commenting out the broken E2E test, so that Travis would pass again.

The conflict of 1 & 2 was a result of me not merging master into all open PRs which would have caught that (and which should have had adequate time to finish before the others were merged. Going forward, as I do the larger `phpcs` style fixes/enforcements, I need to do a better job of making sure I'm merging master into any PR that might be affected.

For 3, I am not sure why this was merged given Travis was consistently failing on the E2E test.

For 4, it is not clear what the investigation steps were (if any) to determine why said test was failing, and how it might be fixed before it was commented out. For this issue that was made, there's no attached people to the issue, so it's not clear to me what was setup to get this resolved. It would be good to hear why it was determined it was best to ignore this test, and if it's just a question of adding more documentation to https://submitty.org/developer/end_to_end_tests or some other issue.

**Comment by bmcutler** [comment]
I can't remember the exact decision making.
But I believe I decided to comment out the single test -- since it was blocking other tests from running -- so we could verify that the errors were apparently isolated to a single test.  This allowed us to proceed with testing and merging other PRs.  
I made an issue to make sure we [someone] circled back and debugged that single test soon.
Time constraints led to imperfect software development.
