### ISSUE TITLE
Display error messages when CSRF check fails in development env

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#4773]
The router checks csrf token if the method is POST. If the check fails, in the case of web access, you will be redirected to the homepage. When I first designed this (https://github.com/Submitty/Submitty/pull/3980#discussion_r301152578), I assumed that it is a rare case that a normal user doesn`t have a csrf token unless they are trying to attack Submitty. However, this behavior may be confusing to developers who accidentally forget POSTing CSRF tokens.

Let's add error messages or something like that in development environment (debug environment) so that developers know the cause of the problem.

From https://github.com/Submitty/Submitty/pull/4772#discussion_r345558204

**Comment by elihschiff** [comment]
I am going to close this issue because it looks like it has already been fixed (feel free to reopen if I am missing something). When I modify a form to have an invalid csrf token I get this error
![image](https://user-images.githubusercontent.com/18558130/76717695-c45d3c80-670a-11ea-9b11-1dbece17de99.png)
