### ISSUE TITLE
Course Materials Download Folder Behavior Using Section-specific Materials

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#4928]
**Describe the bug**
Presently if a folder is in course materials, and section-specific material is in the folder, the download button will be available for that folder as a student. The bug is two fold:

1. If no materials are visible to that student, they see an empty folder with a download button. Clicking it correctly gives a permission error, but it is confusing the to the user.
2. If materials are available to that student but some materials are not visible to that student because they are unreleased/for other sections (may require both criteria), then clicking the download button next to the folder will also cause an error.

**Expected behavior**
1. If there's nothing released for that student, then the download button shouldn't appear. (Possibly the entire folder shouldn't appear).
2. If the download button exists and there are materials that the student can see, the download button should not throw an error, but should let the student download only the files they have access to in that folder. Alternately, the button should never be visible when using section-specific materials in a folder.

**To Reproduce**
1. Add a folder to course materials
2. Add a file inside for only section 1
3. Add a file inside for only section 2
4. Have a student in section 2
5. As the student, go to course materials, click download next to the folder.
6. Move the student to section 1
7. As the student, go to course materials, click download next to the folder.

**Comment by mukul-kmr-jha** [comment]
@holzbh while working on this issue I realized that if an empty folder (for the current user) is tried to get downloaded it does display the error message but it's not the correct error message. It says  *Your section may not access this file.* instead of  *You do not have access to this folder*. Another problem (caught from the @shailpatels [comment](https://github.com/Submitty/Submitty/pull/4939#pullrequestreview-345590582)) is that url hacking is possible for any course material files. 
 @bmcutler To address these, should we modify this issue itself or should I create another issue for this?

**Comment by shailpatels** [comment]
You don't need to create a new issue, if the fix for the URL hacking is small you can add it to your open pr that's related to course materials.

If it's larger just open a new pr to fix it, we typically don't want to draw attention to security related issues publicly on GitHub those issues are discussed internally.

I believe this issue existed before and got resolved if u look for closed prs you might be able to find a solution you can reuse for this too.

**Comment by mukul-kmr-jha** [comment]
I think this issue is resolved in the linked PR #4939
