### ISSUE TITLE
error check for forgot-to-build this assignment

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#496]
right now there's an error:

There are currently no released gradeables. Try checking back later.

**Comment by MasterOdin** [comment]
This happens because there's no config json for a newly created gradeable and the system won't indicate to the user that this is the case. We should be giving better messaging about this such that if the user attempts to go to submission for an un-built gradeable, an error message is displayed to the user (not an exception) that "This assignment has not yet been built and cannot accept submissions".
