### ISSUE TITLE
Database datestyle unspecified

### ISSUE THREAD

**Issue by Mat2095** [Submitty/Submitty#5365]
I'm in the process of setting up an instance of Submitty on a fresh Ubuntu 18.04-VM.
I tried adding a new term with the sbin/create_term.sh script.
The script expects dates in the 'MM/DD/YYYY' format.
However, when I entered '09/30/2020', I got an unexpected error because the database expects dates in the ISO-DMY datestyle.

My postgresql-config defines `datestyle = 'iso, dmy'`. I assume that is because I'm located in Europe.
I think since Submitty sets up postgresql and the databases and relies on a specific datestyle, maybe it should set the datestyle for those databases instead of relying on the default value.

**Comment by Adarsh7825** [comment]
Hello, I would like to work on this!

**Comment by thegame615** [comment]
Hello! I know it's been a long time, but I was unable to reproduce the issue.  I do have an idea of where the problem may have come from however.

If you use the script as:

"create_term.sh  [-a|--amend] <term>  '<name of term>'  <start date>  <end date>"
or
"bash create_term.sh  [-a|--amend] <term>  '<name of term>'  <start date>  <end date>"

I did encounter an error with the date when I used the script as:
"sh create_term.sh  [-a|--amend] <term>  '<name of term>'  <start date>  <end date>"
Which may be because of how the script reads arguments, however I am not sure. I am sure however that it does not have to do with the datestyle. Please reach out if this still continues to be a problem (Although it has been a long time now).
