### ISSUE TITLE
"Print to PDF" a Notebook gradeable

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5646]
**What problem are you trying to solve with Submitty**
The instructor has formatted a quiz/test as a Submitty Notebook.  
Can the student download a PDF of the quiz/test?  
The student may wish to print it on paper, fill it out, then scan & upload (depending on what the student wants to be uploaded).

What does each standard browser "print page" to PDF to with a notebook gradeable?  
Can we do better?
Remove the topbar/sidebar/footer, have page breaks between widget items as appropriate... ???

**Comment by bmcutler** [comment]
@elihschiff & @Kevin-MM -- 
This is not currently a top priority feature request.
But please share your thoughts on this issue.  
Thanks

**Comment by elihschiff** [comment]
I dont think it is browser based, I think it might be os based. Because the os has to have a fake printer that in fact prints to a file. That said I just tested on firefox and chrome on linux as well as on windows and they all have a print to file. However at least for me on linux, in its current state the page would not really be usable to hand write a test on due to formatting so we would need to change the look of the page, or make different print optimized layout for just when you print. 

To hide/show an element only when printing one can use theses classes in bootstrap https://getbootstrap.com/docs/4.3/utilities/display/#display-in-print

We can also add a print button for convenience (which would do the exact same thing as pressing ctrl+p) using this https://developer.mozilla.org/en-US/docs/Web/API/Window/print

**Comment by bmcutler** [comment]
You just reminded me...   we have a "print" button the lab checkpoints page.
e.g.:

http://localhost:1501/courses/f20/sample/gradeable/grading_lab_rotating/grading/print?section=1&section_type=rotating_section&sort=

We used to print paper copies of the lab checksheets!
