### ISSUE TITLE
Bad Link on RCOS Class Submitty

### ISSUE THREAD

**Issue by ianmccaffery** [Submitty/Submitty#5869]
**Describe the bug**
Browsing through the RCOS submitty, I noticed that the "course home"
link is not set to open automatically in a new tab.
**Expected behavior**
Expected the link to open course home in a new tab, as it is not an interior link (it sends to a diff webpage)

**To Reproduce**
1.  Enter RCOS submitty
2.  Click "Course Home"
3.  See error

**Configuration**
 - OS: Windows
 - Browser: Chrome

**Screenshots**

**Additional context**
Prof Turner sent me here to report this.

**Comment by bmcutler** [comment]
This is a much debated topic and not all users will agree on the desired behavior.

Here's a blog explaining the argument:
https://medium.com/the-metric/links-should-open-in-the-same-window-447da3ae59ba

Not forcing a new tab is intentional choice in Submitty.
Some courses & users prefer it to open in the same window.  
users who prefer to open a new tab, can do that explicitly
(shift-click or whatever is the shortcut on their browser/OS).
