### ISSUE TITLE
Why is there Javascript on the buttons on the navigation page?

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#592]
The buttons to enter the homework submission page or to enter the TA grading page include a Javascript function.  Is not necessary for current functionality.  (Did we have something else planned for the buttons?  I couldn't think of what else would be needed.)

Question/Suggestion to remove from @toshipiazza.

**Comment by MasterOdin** [comment]
Because to get the `<button>` tag to go somewhere when you click them you either (a) wrap them in a form or (b) use an onclick JS event. The latter is a lot cleaner than the former and I think more clear on what the desired effect is.

However, you should be able to change the `<button onclick='link'>text</button>` to `<a class='btn' href='link'>text</a>` without things breaking.

**Comment by chrjguill** [comment]
I believe for the buttons, you could convert them to `anchor` tags seamlessly, but if for whatever reason you still need to execute some javascript to handle the link traversing, you could do something like:
`<a class="btn" href="link" onclick="functionName()">`, where `functionName` returns `false` at the end to block the browser from handling the regular click event, but also still allow right click -> open in new tab for the links.

I don't think that the javascript is necessary at all and just impedes functionality, but in case it _does_ do something, somewhere, that's what'll need to be done.

**Comment by MasterOdin** [comment]
From #764:

> This issue (and #592) has work already done in the issue_764 branch. The main issue is that changing to `<a>` tags instead of buttons breaks the styling somewhat so whoever does this needs to fix that and then this should be ready to go.
