### ISSUE TITLE
Edit link url for course material link

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5934]
**What problem are you trying to solve with Submitty**
If the instructor typos the url, when uploading a course material link item,
currently they have to delete the item and re-add the item.

Let's let the edit the link url.

**Comment by Christiankoo** [comment]
Can i take this?

**Comment by arya2331** [comment]
Hi @bmcutler , I am new to submitty and wanted to start with this issue. Can I go ahead?

**Comment by arya2331** [comment]
I have started working on this. Should the instructor also be able to replace files or just edit URL?

**Comment by shailpatels** [comment]
Hi @arya2331 , sorry for the late reply but due to how our GitHub organization is setup we cannot assign external users to an issue. But if no one else is assigned/working on it feel free to work on it! If you make a pull request we would be happy to go through the review process and try and get it merged.

To answer your second question, just editing URLs should be fine for this issue. Replacing files is a bit out of scope and an instructor is less likely to accidently upload the wrong file compared to mistyping or using a broken link.

**Comment by arya2331** [comment]
Where should I give the option to edit the link URL ? In edit coursematerial dialogue box or outside ?

**Comment by arya2331** [comment]
@shailpatels also can you help me with this issue? I have read some code relevant to the course materials but I am not getting where are the links stored. I understood that in uploadcoursematerials.twig we submit URL, But how can I edit it. I have tried using Javascript variables but that did not. Please help me. Thanks

**Comment by shailpatels** [comment]
@arya2331 The edit course dialogue box would make the most sense to me.

We use a model view controller architecture for the site, the twig files are the last step and are usually called by a view file.
Take a look at `site/app/controllers/course/CourseMaterialsController.php` and `site/app/views/course/CourseMaterialsView.php`

Take a look here at how controller functions are called from the front end
https://submitty.org/developer/development_instructions/router-response

**Comment by beardbytes** [comment]
Hey @shailpatels. I really want to make a contribution to this issue!
Please guide me how to proceed
