### ISSUE TITLE
Add documentation (& pictures!) for Submini/Polls to submitty.org

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#6057]

**Comment by sohamsshah** [comment]
Hey can I also work on this?

**Comment by BenKelly99** [comment]
This issue is a little different from our normal ones since it's updating our development/user guide website with information about the new Submini feature. I'd recommend looking for an issue that gets you familiar with our main code base. If you look through the issue tracker for "Good First Issue" tagged issues, they should be a good place to start.

**Comment by sohamsshah** [comment]
Ohh. Thank you so much for help 😁
