### ISSUE TITLE
Have CONFIGURE_SUBMITTY.sh write out to a json file

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#607]
Instead of having to do tons of seds through the system we should have configure write out to 1+ config files that are then used around the system in place of the sed replaces. Some discussion of how this might work is needed.

**Comment by MasterOdin** [comment]
These files would be stored in ${SUBMITTY_INSTALL_DIR}/config (or something like that) and would contain:
- Path information (install, data, repository, svn, logging)
- Database information
- User information (HWPHP, HWCGI, HWCRON, etc.)
- Group information
- URLS for the system
- etc

These files would be needed then by scripts located both in the ${SUBMITTY_INSTALL_DIR} and ${SUBMITTY_DATA_DIR}. Possible solutions for this would be to either replicate the json files in multiple places or use symlinks.

**Comment by bmcutler** [comment]
Does this file contain the hsdbu password or other sensitive information?  Might not be as simple as storing all configuration details in a single file, depending who needs access to it.

**Comment by bmcutler** [comment]
Addressed in PR #1007  

Instead of a json file (that could happen maybe later), generates short bash script with these variables. 
This allows manual editing after CONFIGURE_SUBMITTY.sh has been run.
Also, when INSTALL_SUBMITTY.sh is edited, re-running CONFIGURE_SUBMITTY.sh is not necessary.

Further re-write are low priority.

Reopen new issue with specific goals as needed.
