### ISSUE TITLE
Revise json file formats of the poll/subminis

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#6149]
Now that I'm working with actual course data, I have feedback for the exported formats
(let's try to get these changes in quickly)

* exported file names are non-intuitive.  let's revisit.  how about poll_questions.json and poll_responses.json?  

* the "data" file is missing "status" ("open", "closed", "ended" ... )

* why is top level an associative array in the "data" file, but a simple array with "id" field in "responses" file.  probably just make both an array.

* id is a string in the data/questions file, but an integer in poll_responses.  let's be consistent.

* order the items starting with the smallest id (currently it appears to be starting with the largest)

**Comment by BenKelly99** [comment]
@bmcutler Some thoughts
- I'll rename to those. For the download I included the course, semester and date so that it would be easy to differentiate but if that's not necessary I'll get rid of that.
- I didn't include status because if, say, you import them into a new semester, you wouldn't want them all to start as ended which they probably would be. If that's not really a concern I'll add that field.
- Do you mean both are simple arrays or both are associative arrays? Can do either.
- Yeah this is due to how PHP encodes arrays (all keys are strings). I'll get it to be consistent.
- Will reverse the order

**Comment by bmcutler** [comment]
Sure, leave the additional info in the file names (mostly I'm just asking for more intuitive core naming of questions vs responses)

Status is mid semester when there may be future polls that don't have responses yet, and should not be displayed to students.  If the file is used to import to a new course, that field will be irrelevant and can be ignored.

I think simple array is good enough.  Then you can keep the id as a an integer everywhere.

**Comment by BenKelly99** [comment]
Sorry for the confusion -- but for importing the polls do you mean that the status field can be ignored? (Status defaults to closed - cannot respond and cannot view).

**Comment by bmcutler** [comment]
they are different use cases - simplest to have all of the information in the file, and the use cases can ignore whatever they don't need.

status is relevant in rainbow grades
status / dates will be ignored for uploading to a new course.

(note: status may be redundant information given the open/close dates fields --  I don't remember where we left that design/implementation)

**Comment by BenKelly99** [comment]
Gotcha.
