### ISSUE TITLE
Submini - poll image is lost when poll is edited

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#6254]
**Describe the bug**
I create and save a poll with an image.
I return to edit the poll (just edit the text), but I lose the image.
I have to upload the image each time I edit anything about the poll.

**Comment by BenKelly99** [comment]
Did you check to see if not uploading the image again actually removes the image? I think if you don't select a new image it keeps the existing one (which means you can't remove an image once it's there which might be a problem). The tricky thing is that as far as I can tell you can't set the value of a file input due to security concerns, so there's no way to populate that field with the existing image.

**Comment by bmcutler** [comment]
Yes, it was gone after I made a minor edit to the text.

**Comment by bmcutler** [comment]
Oh, also, it would be nice to add some simple max image width (& height) to the image...
I upload an image that was ~1400 pixels wide and it scrolled off the right edge of the screen.
Keep the original image resolution, but use the browser to set the image to a reasonable width.
