### ISSUE TITLE
popup box still happens at 20 submissions warning about a penalty

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#640]
(even though the max submissions was changed in the config.json)

need to hook up the popup to the new test case...

**Comment by ZishanHuang** [comment]
Currently the max_submissions is set from the COURSEPATH/config/build/build_ASSIGNMENTID.json file. I tried changing that file manually and the pop-up messages did change accordingly.
I think the problem is that, the max_submissions from config.json is not written into the build_ASSIGNMENTID.json when instructors run the BUILD script?
