### ISSUE TITLE
Add stylelint for linting CSS files

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#6417]
**What problem are you trying to solve with Submitty**

We use eslint for JS linting, phpcs for PHP linting, flake8 for python linting, but do not use anything for linting CSS, meaning we end up with discrepancies between the various files.

**Describe the way you'd like to solve this problem**

We can use [stylelint](https://stylelint.io/) to handle linting CSS files, and keep them consistent.

**Comment by williamjallen** [comment]
I support the idea because there are few reasons not to add this.

Unfortunately, the biggest issue I see with the stylesheets right now is the fact that there are so many different files that naming conflicts begin to occur.  This could be eliminated by switching to SCSS at the same time.  SCSS can work alongside CSS so it could be a gradual transition.  In addition to the many other great features of SCSS, we would get free minification and packaging which could potentially improve the load time on first load.  We could also install one of many packages for ensuring maximal browser support--they automatically add `webkit` and `moz` prefixes when necessary amongst other things.

**Comment by MasterOdin** [comment]
Please feel free to open a new issue proposing to moving to SCSS, and why it would be beneficial. The benefits of using stylelint and the benefits of using SCSS are decently orthogonal to each other and can be done relatively independent of each other.

**Comment by williamjallen** [comment]
Ok, I've been thinking about SCSS for a while and will make an issue sometime today.  The only reason I posted was because if we decide to move to SCSS, that would make stylelint obsolete as we would have to move to another linter which supports SCSS.

**Comment by MasterOdin** [comment]
Stylelint can handle parsing SCSS files and then there is https://github.com/kristerkari/stylelint-scss which is a plugin to add SCSS specific rules.

**Comment by williamjallen** [comment]
Ok, yeah, that looks good then.  I didn't know stylelint supported preprocessors too.

**Comment by williamjallen** [comment]
Is this issue in need of an assignee?  I'd be willing to work on it if there isn't already an assignee.
