### ISSUE TITLE
Future Grade Calculator

### ISSUE THREAD

**Issue by alicebibaud** [Submitty/Submitty#6826]
**What problem are you trying to solve with Submitty**
There is currently no way to predict what your grades will be in the future through Rainbow Grades.  You need to calculate by hand, or just do the best you can (yikes!)

**Describe the way you'd like to solve this problem**
Giving students the option to test out different fields in the table to recalculate section and final grades on the fly may help this.

**Describe any potential alternatives you'd tried to solve the problem**
People calculate their potential future grades by hand, using calculators and professor-given formulas right now.  This is fine; just something that might automate an otherwise inconvenient process.

**Additional context**
I had to do a report on an open source technology for Software Design and Documentation, and ended up choosing Submitty as my FOSS.  It's super long, but feel free to take a gander at what I've written and suggest any changes / point out any errors:

https://docs.google.com/document/d/1-dPIh-sufIz6W3ZB6JRIF6Zkcb9j82PN1jkQDcy921U/edit?usp=sharing

**Comment by bmcutler** [comment]
This issue is not feasible without a complete rewrite of Rainbow Grades.  Rainbow Grades is an instructor tool, and is a tool for displaying the current state of your grades in the instructors spreadsheet.  It is not a tool for playing "what if" with future grades.

The primary challenge in delivering this feature is the huge variety in how instructors design their grading syllabus (grading curves, "drop lowest", extra credit, makeups, etc.)  It is not possible to provide a "what if" tool without significant instructor involvement for EVERY course.  Without instructor involvement the accuracy of any final grades predictor is highly questionable and misleading.

While this is a popular feature request from students, I am closing this issue because it is not practical.
