### ISSUE TITLE
Gradeables with no due date should not show time remaining 

### ISSUE THREAD

**Issue by shailpatels** [Submitty/Submitty#6999]
**Describe the bug**
The time bar for showing how much time is available until a gradeable is due shows up when a gradeable is set to have no due date and says "Your time remaining past due" which is not true

 

**Expected behavior**
The time remaining should not appear on a gradeable with no due date

**To Reproduce**
1.  Create a new gradeable of any kind that can support no due dates
2. Open the gradeable for submissions
3. Go to submissions page for that gradeable on any user

**Configuration**
 - OS: MacOS
 - Browser [Firefox
 
<img width="343" alt="image" src="https://user-images.githubusercontent.com/12129065/131602836-8cb6e07a-9a24-4c3b-bac2-32bec26f21cd.png">

**Comment by cjreed121** [comment]
This should have been fixed in https://github.com/Submitty/Submitty/pull/6983. It is expected behavior that a gradeable with no due date can have a timer/progress bar. An example of this case could be a course that has gradeables open all semester but instructor only allots 1 hour to work on each. Did you have the latest master when you found this bug?

**Comment by shailpatels** [comment]
@cjreed121 Yes you're right, I saw that when checking out a branch on an older baseline, the current master appears to be fixed
