### ISSUE TITLE
UI bug with crumbs on Office hours queue page

### ISSUE THREAD

**Issue by HenrikLam** [Submitty/Submitty#7008]
**Describe the bug**
External link icon is a different color and highlights on hover in the Office Hours Queue Page, however, this is not the case for other website. This problem seems to be unique to dark mode.

**Expected behavior**
The icon should appear the same across the site

**To Reproduce**
1.  Login
2.  Go into office Hours Queue page for a course
3. See error

**Configuration**
 - OS: Windows
 - Browser: Chrome

**Screenshots**
On office hours queue page
![image](https://user-images.githubusercontent.com/49821332/131901183-3bfdd34d-6324-4dd2-9fe6-599904fd898b.png)

Everywhere else on the page
![image](https://user-images.githubusercontent.com/49821332/131901248-65f4af31-6635-4ac2-ac00-1ea74edf35ad.png)

**Comment by Gulsonish** [comment]
Hey @HenrikLam , Can you suggest me files name and connected files name as I can't run submitty on my pc because of storage and pc performance issue and I am unable to find those attributes on Office hours queue page and I can fix this by examining the whole connected code. 
So, Please to tell me little more about coded files.

**Comment by HenrikLam** [comment]
Try editing the entry in the `officeHoursQueue.css`. Just from inspecting the html, it looks like the color set by `server.css` is getting overwritten by this css file since the buttons since they are under `i.fas`. However, you may also need to edit the `twig` files under the `/site/app/templates/officeHoursQueue` directory to use a new class to signal the color styling.
