### ISSUE TITLE
Time being helped in the Office Hours Queue is not computed and shown correctly

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#7070]
**Describe the bug**
When a TA/instructor/mentor clicks the "Help" button to start helping a student in the Office Hours Queue, the "Time" column value is not show correctly with some negative values first before the "0:00" is reached. In other words, when I click "Help" for a student, the Time column first shows -1:-1, then -1:0, and then 0:0 after which it starts counting correctly

**Expected behavior**
The timer should start with "0:00" instead of negative values.

**To Reproduce**
1. Open the Office Hours Queue page as an instructor.
2. Select the student to be helped and click "Help".
3. Observe the timer with incorrect values as shown in the animated screenshot.

**Configuration**
 - OS: Windows 10 Enterprise x64 20H2, 10.0.19042, Build 19042.1110, Windows Feature Experience Pack 120.2212.3530.0
 - Browser: Mozilla Firefox 91.0.2 (64-bit)

**Screenshots**
![8kq4wippJv](https://user-images.githubusercontent.com/7108039/133120882-3bf3e6a8-1d18-4dce-97f7-ee78f4ae8130.gif)

**Additional context**
N/A

**Comment by williamjallen** [comment]
I believe that this issue is the result of some sort of time difference between your local machine and the Submitty server on production.  I am seeing the same issue while managing the queue for another course and can confirm that it does not appear to happen on my development VM.  I looked into the issue and the initial value ultimately comes from this function which appears to use the server system time: https://github.com/Submitty/Submitty/blob/74b30729ede0d1483559221d3fa1fde365b059a4/site/app/models/OfficeHoursQueueModel.php#L135-L139

One potential resolution for this would be to always simply make negative times display as 0 but perhaps there is a better fix.  In this particular case, perhaps @bmcutler needs to re-sync the system time on the server?

**Comment by williamjallen** [comment]
Re-syncing the system time seemed to fix this issue and it has not returned so I will close this issue.  If the issue re-appears, re-open the issue and we can potentially discuss better options for preventing this in the future.
