### ISSUE TITLE
Show correct answer to poll after it is closed

### ISSUE THREAD

**Issue by loadedskiffer** [Submitty/Submitty#7352]
**What problem are you trying to solve with Submitty**
Currently there is no way for a student to view the correct answer of a poll after it is closed.
There is a setting that allows students to see the histogram but that doesn't specifically say the correct answer.

**Describe the way you'd like to solve this problem**
We should show the histogram but instead of blue, color the correct answer green so it is clear which one is correct.

**Comment by bmcutler** [comment]
Additional feature request:
The instructor still needs control on if and when to release the information about what answer is correct.

Use cases:

1. While the poll is open for response, the instructor may wish to allow students to see the current histogram of answers...  but not yet view which answer(s) are correct.

2. Once the poll is closed, the instructor may not wish to display which answers are correct -- because that information may be misleading.  Sometimes a poll has one perfect answer that will receive full credit but it also has a partially correct answer that the instructor also decides to give full credit.  It would be misleading to show both of them as equally worth full credit.   In this case the instructor may want to communicate this in other ways.

**Comment by tlasich** [comment]
That makes sense! I hadn't thought of those scenarios. I will look into this! Thank you.

**Comment by bmcutler** [comment]
Similar to the drop down menu of when to show that histogram is visible (never, after poll ended, always).
It would be good to have the same drop down menu for when to show the correct answer on the histogram.
And additionally/alternately I think we may want to have the option of showing which answers are correct next to the questions even when the histogram is not revealed to the students.

**Comment by tlasich** [comment]
For the last part about showing the answers next to the questions even when the histogram is not revealed, do you mean to add a column to the table in this view that shows the correct answer if that setting has been enabled by the instructor?

![poll_list](https://user-images.githubusercontent.com/78006924/145661456-0cc3b367-e147-4bc4-9dfa-7886a3db4bd9.png)

Or do you mean to display that in this view?

![season_poll](https://user-images.githubusercontent.com/78006924/145661497-62461563-c86d-4bfd-948c-399152667175.png)
