### ISSUE TITLE
Add SAML 2.0 authentication support

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#7652]
RPI is moving towards having SAML be the suggested login mechanism for applications as it allows them to enforce SSO with login requirements to the RPI network. At some point, Submitty will be required to tie into this setup, or risk losing its ability to operate outside the firewall.

RPI uses the [Shibboleth](https://en.wikipedia.org/wiki/Shibboleth_(software)) as its identity provider that we need to integrate with, but the hope is that we can have a fairly generic SAML 2.0 authentication method. 

Some resources:
* https://shibboleth.atlassian.net/wiki/spaces/CONCEPT/overview explains the core concepts of how SAML works, where the SP would be Submitty, and IdP is RPI.
* https://github.com/winstonhong/Shibboleth-SAML-IdP-and-SP is a possible demo app, where we'd look to replace the SP side of things
    * https://github.com/winstonhong/Shibboleth-SAML-IdP-and-SP/blob/e89d06c91c72b2072f546ae0e9acc139583ad41d/LDAP-Dockerized-CentOS/users.ldif can be modified to provide a handful of users to authenticate with for testing for Submitty.
    * https://github.com/CSCfi/shibboleth-idp-dockerized provides a more up-to-date version of shibboleth, not sure how important that is
* Possible PHP libraries:
    * https://www.lightsaml.com/
    * https://github.com/onelogin/php-saml
    * https://simplesamlphp.org/

The workflow would look something like:
* Document setting up a IdP instance in Vagrant
* Get it working on Submitty
    * Create new SamlAuthentication class under https://github.com/Submitty/Submitty/tree/master/site/app/authentication
    * Will we need to create a new "step2" login endpoint such that user hits "login on Submitty" -> "gets redirected to SAML IdP" -> "logins on IdP" -> "redirects back to Submitty"?
    * Will need to document steps of getting SP metadata to provide to IdP
    * Configuration details to library we use?
    * What questions would we need to ask to RPI admins for production (e.g. assertions we can get)? 
* Get details for integrating with RPI from sysadmins
    * Will need to generate metadata.xml from Submitty to give to sysadmins, plus get details on the SAML assertions structure

**Comment by sama8** [comment]
Sharing, if relevant -> [SAML Jackson](https://github.com/boxyhq/jackson)

**Comment by cjreed121** [comment]
@MasterOdin I gave this a try with a mock IdP server using the php-saml library from onelogin. I was successfully able to implement login functionality. As soon as you hit the login endpoint it will redirect you to the IdP. Once you sign in with IdP it will then take you back to Submitty and verify your request with the IdP. Assuming it's valid you get generated the standard Submitty token and can continue using Submitty as normal. I had some issues with logout (SLO) that I'm still investigating. Of course a normal logout could just work where we just delete your session but I'm assuming we would want to do SLO operations as well?

One issue we will have to address with this is how we want to handle vcs login in SAML auth mode. Right now that uses your password but adding SAML would eliminate Submitty being able to verify your password. I see 2 solutions but maybe you have other ideas:
1. We could finish #4408 before this issue is finished. Although it would force all users to do ssh git in SAML auth mode.
2. We could have git auth tokens that just replaces your password. Essentially like GitHub's personal access tokens.

It seems that all we would need from RPI for this to work is an entityId, the SSO url, the SLO url (if we do this), the x509 public certificate, and a list of attributes we can access.

**Comment by MasterOdin** [comment]
I think option 2 is good choice, and is expected to be able to do that in any system that has MFA. It would also be the easier option to implement.
