### ISSUE TITLE
Server error when attempting to view thread history

### ISSUE THREAD

**Issue by wusatosi** [Submitty/Submitty#7677]
**Describe the bug**
Server returns error when attempt to view a post's (thread description/ reply) history.
Error message:
```
app\exceptions\OutputException (Code: 0) thrown in /usr/local/submitty/site/app/libraries/Output.php (Line 360) by:
            throw new OutputException("{$e->getMessage()} in {$e->getFile()}:{$e->getLine()}");


Message:
Variable "render_markdown" does not exist. in /usr/local/submitty/site/app/templates/forum/RenderPost.twig:1

Stack Trace:
#0 /usr/local/submitty/site/app/controllers/forum/ForumController.php(1111): app\libraries\Output->renderTwigTemplate()
#1 unknown file(unknown line): app\controllers\forum\ForumController->getHistory()
#2 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(241): call_user_func_array()
#3 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(219): app\libraries\routers\WebRouter->run()
#4 /usr/local/submitty/site/public/index.php(131): app\libraries\routers\WebRouter::getWebResponse()
```

**Expected behavior**
The history of the post been shown. 

**To Reproduce**
1. Create a thread/ reply
2. Modify it
3. Click "Show History"

**Configuration**
 - OS: Windows 10
 - Browser: Edge

**Screenshots**
![image](https://user-images.githubusercontent.com/26424577/155832090-109725a2-baf7-4429-a2e9-383b1f716a53.png)
![image](https://user-images.githubusercontent.com/26424577/155832109-a46210de-0a85-4478-ab8e-87a658dd59af.png)

**Additional context**
Is this feature actually needed?

**Comment by wusatosi** [comment]
Controller:
https://github.com/Submitty/Submitty/blob/c6c777257b5ab534e950925cf3ab9899c33e029e/site/app/controllers/forum/ForumController.php#L1096-L1132

Twig (single line file):
https://github.com/Submitty/Submitty/blob/c6c777257b5ab534e950925cf3ab9899c33e029e/site/app/templates/forum/RenderPost.twig#L1

**Comment by shailpatels** [comment]
Just to answer your question under additional context @wusatosi , the post history is useful if a student posts something they're not allowed (like solutions to hw for example), Submitty saves it - even after edits so an instructor can review later.

This bug was probably not noticed since twig missing variables throw an error only when debug is enabled in `config/database.json` - on production the show history function works fine since an unset variable is considered falsey by twig/php without strict checking
