### ISSUE TITLE
Restoring Stars when Graders Restore Students in Queue

### ISSUE THREAD

**Issue by NiaHeermance** [Submitty/Submitty#7806]
Sometimes graders may help the wrong person. When this happens, a grader will end the help session and restore the student to the queue. If the student had stars, there stars are lost. Perhaps the Restore button should restore the most recent amount of stars a student had.

**Comment by cavallefano** [comment]
is this issue still open? i can work on it

**Comment by Eceptonsu** [comment]
> is this issue still open? i can work on it if it is

Yeah I am currently on it.

**Comment by shailpatels** [comment]
> is this issue still open? i can work on it if it is

Hi @cavallefano, if you look at the issue you can see any linked PRs that may close this issue, for this one its #8482 
If you're interested in contributing feel free to look through the good first issues where there's either no one assigned or no PRs linked to it.

Due to how our github organization is setup we cannot assign external users to issues but you can always comment your working an issue or make a PR to fix one and we can work through getting it reviewed and merged

**Comment by Robin-Anmol** [comment]
Is someone working on this/done with this issue or I can solve this and make a PR?

**Comment by williamjallen** [comment]
Hi @Robin-Anmol, there is currently a PR linked to this issue which will close it when the PR is merged.  Feel free to review https://github.com/Submitty/Submitty/pull/8482 and provide feedback on the changes made.

**Comment by Eceptonsu** [comment]
> I would like to work on this issue if possible please assign

Hi, I have a PR that is linked to this issues. Feel free to review #8482 and see if it fixes the issue. Thanks.
