### ISSUE TITLE
Automate Testing of Database Migration Correctness

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8076]
**What problem are you trying to solve with Submitty**

We don't always perfectly follow our migration instructions
https://submitty.org/developer/development_instructions/migrations#writing-new-migrations

Specifically, is the .sql files are manually edited instead of writing a migration and dumping the resulting .sql file.

If the PR is more complex, the database changes might have been revised or tweaked and something becomes inconsistent.

**Describe the way you'd like to solve this problem**

If an open PR edits:
* migrations/migrator/data/submitty_db.sql (the main submitty database schema)
OR
* migrations/migrator/data/course_tables.sql (the course database schema)
OR
* adds a migration in /migrations/migrator/migrations/master 
OR
* adds a migration in /migrations/migrator/migrations/course

Then let's do a GitHub Action CI test to verify database consistency:
1. Checkout the current main branch.  
2. Create new main and course databases from scratch from the main branch.
3. Switch to the PR branch.  Apply the migrations
4. Dump the databases -- save these files.
5. Recreate the main and course database from scratch on the PR branch.
6. Dump the database -- save these files
7. Compare the database dump files -- fail the test of they are not identical.

Note: If none of the folders/files above have been edited, the GitHub action can shortcircuit and pass.

**Comment by cjreed121** [comment]
This would definitely be a helpful tool. One potential issue with the steps is that we don't want to compare `main -> current_branch` but instead `latest merge point between main and current_branch -> current_branch`. Otherwise if main contains a migration which the current_branch doesn't have then this test will automatically fail and people might get stuck doing more merge commits for migrations. I think we might be able to use something like `git merge-base` here but some testing should be done.
