### ISSUE TITLE
Rebuild gradeable stuck on `in rebuild queue`

### ISSUE THREAD

**Issue by poorna2152** [Submitty/Submitty#8152]
**Describe the bug**
When `Rebuild Gradeable`  button of a Gradeable is clicked build status is stuck on ` is in the rebuild queue`.

**Expected behavior**
Build status should go into  `Gradeable build complete` after some time.

**To Reproduce**
1. Log in as an instructor
2. Go to a edit gradeable page for any gradeable
3. Click the `Submissions\Autograding` tab
4. Click the `Rebuild Gradeable` button

**Additional context**
Managed to solve this using command `apt-get install libgl1` as suggested by @Viyerelu23333

**Comment by Viyerelu23333** [comment]
Just had a look into this issue...  

It is introduced by dependabot in https://github.com/Submitty/Submitty/commit/ba8145ef0db6701ea7d65577f4f569bf3e14376c.  There is also a related issue at `opencv/opencv-python#370`.

**Comment by shailpatels** [comment]
@MasterOdin Yeah switching to opencv-headless I think is the better option since the X11 stuff is never actually used anywhere 
made https://github.com/Submitty/Submitty/pull/8156 to fix this issue with the migration

So far didn't see any issues testing the bulk upload functions since it only uses the core opencv modules
