### ISSUE TITLE
Add user Profile Option for Family/Last Name Initial/Abbreviation

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8436]
**What problem are you trying to solve with Submitty**
We currently assume that the users last/family/sur name should be abbreviated by taking only the first initial.  

* This is correct for users with a single last name.
'John' 'Smith' =>  "John S."

* However, this is incorrect for users with multiple last/family/sur names separated by a space:
'John' 'Smith Jones'  => "John S.J." or "John SJ." or "John SJ"

* Similarly, users with hyphenated last/family/sur names may want both initials:
'John' 'Smith-Jones'  => "John S-J."

* And let's add other standard name abbreviation conventions to this list...

**Describe the way you'd like to solve this problem**
Let's add an option to the user profile page.
By default, we'll chose the first option, to grab the first letter of their family/last/sur name string.
But add radio buttons to let them select one of several other options.
NOTE:  Let's not let them type anything for their last name string.  
It must be based on their preferred last/family/sur name and be 
one of our set of choices above (expanded to include all conventions).

Also, let's have an option to not display anything at all about the last name.
(Make this the last choice in the list.  Displaying some abbreviation about the last name 
is helpful in large classes where multiple users might have the same given/first name)

**Comment by shailpatels** [comment]
Hi @ajjayymahato 

This issue is open and we will accept and review and pull requests attempting to resolve it

Please read the suggestions for new developers here: https://submitty.org/developer/getting_started/index and try and get a developer instance of Submitty running locally.

We cannot assign an issue to someone outside of the Submitty Github project, but if you make a PR we would be happy to review it and try to get it merged. Please try and look at the documentation at submitty.org and if you get stuck on something ask on the general chat in slack.

**Comment by vwaddell** [comment]
Hi, our team @kyminbb @LeoJung1 @01-eric and @jihyochung would like to work on this issue along with issue #8446.

**Comment by Adityaarora08** [comment]
Is someone working on this/done with this issue or I can solve this and make a PR?

**Comment by utkarsh172** [comment]
Hi, @bmcutler i would like to contribute on this issue.
