### ISSUE TITLE
How do I add a new API?

### ISSUE THREAD

**Issue by lacicloud** [Submitty/Submitty#8601]
Hiya,

How is it possible to add a new API endpoint? The API documentation does not say but when I try to add a new API endpoint as follows it always says endpoint not found. I am adding it to HomePageController.php . Thank you. 
```

 /**
     * @Route("/api/mynewapi", methods={"GET"})
     *
     * @return MultiResponse
     */
    public function myNewAPI() {
           return new MultiResponse(
            "hello"
        );
        
}
```

**Comment by williamjallen** [comment]
Did you install after adding that code?  I believe the annotations are now cached and must be updated by running `install_submitty` whenever a new one is added.  I'm not particularly familiar with the API though, so hopefully someone else can chime in if there is a specific API issue I'm unaware of here.

**Comment by jonwk** [comment]
Thanks, it works, I have just tried that now, I have been trying to create a route `api/gradeables`. It didn't work until I ran `install_submitty` in the setup dir again.

**Comment by williamjallen** [comment]
Is your issue resolved? (should this issue be closed?)

**Comment by jonwk** [comment]
I think you can close it, We're both working together (Me and @lacicloud ) and it seems like our issue has been resolved.

**Comment by jonwk** [comment]
Hi about this issue again, so for me to run `install_submitty` for every small change to take place, it's taking roughly about 30 mins for the whole installation. Is there any better or faster way to get around this when updating annotations or adding in new APIs ?

**Comment by MasterOdin** [comment]
There are three different ways to install stuff on Submitty after making changes:

```
    submitty_install             - runs INSTALL_SUBMITTY.sh
    submitty_install_site        - runs .setup/INSTALL_SUBMITTY_HELPER_SITE.sh
    submitty_install_bin         - runs .setup/INSTALL_SUBMITTY_HELPER_BIN.sh
```

If you're only modifying site code, then I'd suggest running the `submitty_install_site` command and that'll avoid futzing with other parts of the system (e.g. autograding, bin scripts). You could also use the [code watcher](https://submitty.org/developer/development_instructions/index#incremental-development-updates) which will automate running `submitty_install_site` or `submitty_install_bin` for you as you make changes.

If `submitty_install_site` remains too slow, I'd be interested to see the output of it since it _should_ avoid the stuff that'll take a while (running `npm` or `composer` unless you're actively editing `package.json` or `composer.json` respectively).

**Comment by williamjallen** [comment]
I believe that `submitty_install_site` clears the caches.  This script should only take a few seconds, and should greatly speed up your development process.

**Comment by jonwk** [comment]
Thank you guys, that is actually so helpful, it's gonna save me so much time !
