### ISSUE TITLE
Discussion forum makes request when body of post is empty

### ISSUE THREAD

**Issue by PythonCoderAS** [Submitty/Submitty#8696]
**Describe the bug**
If the new post text box is empty, a request is still made.

**Expected behavior**
Client-side validation should tell me it was empty without making a full network request.

**To Reproduce**
1. Go to forum post
2. Hit Submit Reply to All

**Configuration**
 - OS: [e.g. Windows, Linux, ...] MacOS
 - Browser [e.g. chrome, safari] Chrome

**Screenshots**

**Additional context**
It doesn't let us post but it's a waste of a network request.

**Comment by sk-2809** [comment]
Requesting to assign this to me
Thanks in advance

**Comment by sk-2809** [comment]
@bmcutler can you please assign this issue to me.
I have gone through codebase, and know how to solve this

**Comment by MasterOdin** [comment]
Hi @sk-2809, due to how our GitHub organization is set up we cannot assign external users to an issue. However, if no one else is assigned/working on the issue, feel free to just post that you're working on it, and then open a pull request! Once you make a pull request, we'll be happy to go through the review process and try to get it merged.

We recommend reading the suggestions for new developers [here](https://submitty.org/developer/getting_started/index) as well as our [How to Contribute](https://submitty.org/developer/getting_started/how_to_contribute) guide to help you get started, and if you get stuck on something, feel free to ask on the general chat on [Slack](https://join.slack.com/t/submitty/shared_invite/enQtMzE1NzgyMzUzNzI5LWZhOGM4NWU4M2U3ZmM2ZmM5NTYwNjk3NTc5Yjg1ZGRlYzU1MjcwYWNkNGYxZjk2YTk3ZmEyODY3MjEyOTc0M2E).
