### ISSUE TITLE
Next/Previous arrow buttons don't save grading inputs in TA Grading View

### ISSUE THREAD

**Issue by maksimt** [Submitty/Submitty#872]
The buttons don't save currently input data, and the system doesn't remember who the last graded student was.

As far as I understand the workflow for TA grading view is that the TA grades a submission, presses enter "Submit Homework Grade" and then is presented with the next ungraded submission. This doesn't capture many possible workflows. (BTW assignments with no submission should just get a 0, I don't see why the grader has to verify there is no submission and confirm the 0.) 

Allowing the next/previous buttons to save currently input sub-grades would allow for several addition workflows:

1. Partial grading. I want to grade problem (1) for all my students before moving on to problem (2), as a result "next ungraded submission" isn't meaningful.
2. It allows me to move through the student list independent of TA<->Section<->Student assignments. Sometimes these are wrong, and I am presented with students who are not in my sections. Sometimes I may want to ignore sections (e.g. if I am grading problem (3) on the exam for all sections).

**Comment by bmcutler** [comment]
Yes, saving the partially completed work by a TA as a "draft" of the homework grade is an open issue, #292   We know it's important, but it's not quick.

Facilitating multiple TAs to grade each assignment (e.g., each TA grades all students for one problem instead of each TA grades the whole assignment for a subset of students), is issue #856. 

We haven't reached consensus on how to handle "no submission" assignments, or assignments submitted too late for consideration.  On the one hand we could just omit them from the TAs assigned work.  On the other hand, its sometimes important to look up a specific student and figure out why they got a '0'.  And sometimes an after-the-fact excused absence is received and the late work should be accepted and graded.  (can't find the issue --if we made one-- where we talked about)

We are aware of some issues with display of your assigned students.  And there might be some errors in the prev/next buttons.   If you can describe a specific reproduceable case (perhaps send this by email -- we need the grader type, gradeable details, whether it's being graded by registration or rotating, what sections were assigned, etc.)

**Comment by maksimt** [comment]
> saving the partially completed work by a TA as a "draft" of the homework grade is an open issue, #292 We know it's important, but it's not quick.

Until draft functionality is added, how difficult would it be to have the forward/back arrows perform the same submit that "enter" does?

If I'm trying to grade "for problems for students" the current workflow is cumbersome. I am required to  go back to the student list, find the student I just graded, pick the next student, load the grading view, reseting the layout/open items, resize them (the layout seems to get forgotten if I do anything except the "grade next" workflow), grade a problem and then repeat. This is too much overhead, especially if there are a lot of problems.

The alternative is the current expected workflow "for students for problems", where the grader grades each student on all the problems at once. In my opinion asking the grader to have the mental context for 5-7 problems in memory makes the system unnecessarily difficult to use.

**Comment by bmcutler** [comment]
The context for this issue is now changed since we are saving grades per "component" (assignment problem).  So this issue can be closed.

Note that we remaining work on issue #1238 (streamlining ta grading for different use cases) will improve ta workflow. 

New issues can be opened for additional feature requests & bugs.
