### ISSUE TITLE
Omitting thread id errors & clears form

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8816]
**Describe the bug**
When an instructor fillis out the "New Gradeable" form, if they say "Yes" to "Is there a discussion forum component... " but they do not fill in the forum thread id, submission of the form will fail, and the form boxes are cleared -- losing the users work/effort.

Note: the forum must be enabled for this course.

<img width="768" alt="Screen Shot 2023-02-02 at 4 21 34 PM" src="https://user-images.githubusercontent.com/5871417/216458284-d9507b12-f4ee-4ec6-882e-36259b2bb20c.png">

<img width="542" alt="Screen Shot 2023-02-02 at 4 21 41 PM" src="https://user-images.githubusercontent.com/5871417/216458298-e80bbcc6-2993-40c8-8fb2-69ca45b610c5.png">

**Expected behavior**
Instead, let's properly treat this form box as a required field and don't allow submission, don't clear & lose the data.

NOTE:  Thoroughly test this form and make sure all other fields are correctly checked for mandatory values, etc. to prevent data loss in attempting to submit with any incomplete form state.

**Comment by Saurabh9542** [comment]
Hello sir, I am intrested on working this issue, please assign me this issue.

**Comment by shailpatels** [comment]
@Saurabh9542 , do not use pronouns unless you are sure that's what the user goes by

due to how our github organization is setup we cannot assign external users to an issue. But if no one else is assigned/working on it feel free to work on it - If you make a pull request we would be happy to go through the review process and try and get it merged.
