### ISSUE TITLE
The "new" color on old forum threads with new posts is gone

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8990]
**Describe the bug**
If a thread contains both posts I've seen and posts I've not seen, the thread on the left bar should be blue, and when I click on it, the thread posts within the thread should be white (old) and blue (new).

Unfortunately, the thread on the left side is NOT blue.  So I don't know what threads have updates.  When I click on them one by one and scroll down, I do see the new posts.

[ I'm unable to quickly point to a recent PR that changed this behavior ]

**Comment by 04vmatsibekker** [comment]
I think I figured out the issue, and it's because if a user makes a thread, the thread will never be considered a "new_thread" even when there are new posts on it because the thread was made by that user. 

When I had the thread be made by a ta, had the instructor view it, and then hadd a student add a new post, the color did change to blue. 

However if the instructor made the thread, and the student adds a post, the color does not change to blue.
