### ISSUE TITLE
Export status of open grade inquiry to Rainbow Grades

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#9112]
**What problem are you trying to solve with Submitty**
If a student has submitted a grade inquiry for a specific assignment, and it has not yet been resolved (it is open), it would be helpful to note that on the Rainbow Grades spreadsheet.  

**Describe the way you'd like to solve this problem**
First, the state of the grade inquiry should be included in the .json file exported for each students in Generate Grade Summaries.  I suggest 3 states.   "None" (never started a grade inquiry), "Open", and "Resolved". 

Ideally we visualize all 3 states in the RainbowGrades output, with "Resolved" being a minor asterisk, and "Open" being a larger more visible tag <-- the instructor should not assign final grades if there is an unresolved grade inquiry!

**Additional context**
related to #5260 

I don't have a final proposal for the visual design -- it should be prototyped and those prototypes presented and discussed by a group. 

Perhaps we outline in red (or some other color) the cells for each student & gradeable that has an active grade inquiry.  The color needs to be noticeable, but should be different than color that is used for other visuals in #5260.

Once the grade inquiry is resolved, perhaps the cell has a thick black border?  Or maybe a symbol (e.g., '!') after the score "83!" to indicate it was resolved.   The symbol needs discussion, we are already using a * for use of a late day and @ for academic integrity.  Those symbols could be redesigned.  

We should have a key at the bottom of the page summarizing the visuals.

**Comment by ziesski** [comment]
![Screen Shot 2023-04-06 at 01 13 17](https://user-images.githubusercontent.com/123261952/230277911-920550b0-895e-4f9e-803b-dff59503c817.png)

I just modified some html from instructor gradebook, and applied possible cases that @bmcutler mentioned. Is this similar to your rough blueprint? 

--- Stuff Barb mentioned in #5260 ---
red outline with a 0 score in the cell = submitted, but too late or not enough late days => automatic zero
yellow outline with a non-zero score = grade override (often used for makeup exams, or other special cases)
empty box, no score = no submission
orange outline with a '?' score in the cell = submitted, but not yet graded
green(?) outline with a non-zero score = grade inquiry in progress
red outline with a @ score in the cell = academic integrity violation on this assignment

**Comment by ziesski** [comment]
@bmcutler Slight progress on the design (or regress) as we discussed last week, the overlapping of the border may lead to confusion, so one of the way to go around is to make the border separate instead, which would thicken the border (because it is now 2px instead of 1px), but overlapping problem is gone. I think this is a bad fix (it looks bad), and I will find a better solution soon. 

![Screen Shot 2023-04-10 at 16 38 14](https://user-images.githubusercontent.com/123261952/230994997-d3a0db4d-724b-480b-a635-e3f747214605.png)

![Screen Shot 2023-04-10 at 16 38 27](https://user-images.githubusercontent.com/123261952/230995013-748df17b-a96c-4acd-b47d-8d73f3b51b77.png)
