### ISSUE TITLE
Minor issues with My Profile pronouns UI

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#9147]
**Describe the bug**

1. On Mac Chrome the width of the selector is too narrow for the default text:
(I actually cannot scroll to see what the rest of the text says)
<img width="591" alt="Screen Shot 2023-04-05 at 12 38 08 AM" src="https://user-images.githubusercontent.com/5871417/229982697-a77cf18b-3671-41d9-b7e0-ca40a412be02.png">

2.  Before I've made a selection, there are multiple options in the dropdown:
  <img width="382" alt="Screen Shot 2023-04-05 at 12 38 46 AM" src="https://user-images.githubusercontent.com/5871417/229982799-38eab048-089b-4448-8e8f-ba8ef7d48746.png">
  But once I've made a selection, there is only that one option:
  (It would be nice to still see all of the options.  Yes, if I clear out my selection, then I can see all the options again, but I don't think that should be necessary.)
  <img width="406" alt="Screen Shot 2023-04-05 at 12 39 03 AM" src="https://user-images.githubusercontent.com/5871417/229983158-d308752b-1ea2-4223-b469-4ce0f0f41984.png">

3.  If I click on the pencil to consider editing my selection, but don't change anything pressing "Submit" does not close the   window.  I just get an error message and the modal stays open.  I didn't notice the error, so it was annoying, I kept pressing "Submit" and nothing happened.  Go ahead and close it when I hit submit, even if I didn't change my pronouns.
<img width="570" alt="Screen Shot 2023-04-05 at 12 39 19 AM" src="https://user-images.githubusercontent.com/5871417/229985196-f573d734-e7a0-40ee-a634-01003dce61b7.png">

**Comment by hansongu123** [comment]
It is possible to redesign this input window, to have it display as a dropdown table with the same width as the window. The code would be easier too.  Just a personal opinion, but this bubble dropdown looks a lot like when displaying a history of user inputs, instead of an input within the required/formatted options. 
Leaking my personal email here, but: 
![image](https://user-images.githubusercontent.com/123511202/230011089-61d163b7-40db-4b4b-9a83-88544b000198.png)
Should be a pretty quick job to re-implement, taking my experience with the similar UI stuff in Submitty.

For Barb's question about the width of the selector's suggestion text, just leave the "Type" out. It'd still make sense and should work no matter the size of the other text how much the page is zoomed in - for the easiest solution. You can also play around with the width of the input window and that text too, to find a better alternative.

Lastly, this is what I found out the last time I was testing the Pronouns branch. On the same input window, I think it would make more sense if the user would be only given the permission to type in it if they selected "custom". And yeah, display the full bar even the user already selected one input, in case of a mis-click.  Put one of the options as empty(- -) too, so it is more conventional over all.

**Comment by bmcutler** [comment]
My requests are for minor formatting revisions only.

The current design that allows & encourages users to type custom pronouns should remain.  We do not want to require them to first select "custom" before typing.

**Comment by hansongu123** [comment]
Cool.

**Comment by mahi-pas** [comment]
About issue 2, I've looked into how to use the data list without filtering and couldn't find anything. 
The closest I found was this: https://stackoverflow.com/questions/41678677/avoid-filtering-of-datalist-items-in-an-input-element
but it didn't work correctly (for me the dropdown didn't show, and when trying the solution in an online interpreter it only showed the dropdown after typing at least 1 character)
