### ISSUE TITLE
Cursor changing when hovering announcement

### ISSUE THREAD

**Issue by EdenBendheim** [Submitty/Submitty#9248]
**Describe the bug**
When I drag my cursor across the border of an announcement, the cursor changes for just a split of a second, as if the border is clickable. If we can figure out what causes it and remove it, that would be nice.

**Expected behavior**
The cursor should never change.

**To Reproduce**
1. Open calendar
2. Find an announcment
3. Hover the border

**Configuration**
 - OS: Mac
 - Browser: Safari, Chrome

**Screenshots**
It only happens for a split second so I could not get a screenshot

**Additional context**

**Comment by 1Shubham7** [comment]
I want to work on this issue, can you please assign it to me?

**Comment by champati-v** [comment]
Hii! @EdenBendheim 
I am new to open source and I am looking for projects to contribute to. I would like to work on this issue, can you please asssign me this one?
Thanks and regards,
Vibekananda Champati

**Comment by Simer13** [comment]
I went through the announcement code section and saw the hover border properties which already contain the border style as none and solid black which is significantly enough to display the right properties, but since there is still an issue it might because of some other changes done in some other part of the code which might be affecting it right now.

**Comment by MohdShahzil29** [comment]
i want to contribute in this project could you please assign it to me?

**Comment by abansal15** [comment]
Hello @EdenBendheim if this issue is currently open could you please assign it to me

**Comment by Zofiskun** [comment]
@EdenBendheim can, you please  assign it to me
