### ISSUE TITLE
Grade Override Page for Instructors not properly working

### ISSUE THREAD

**Issue by Youssef-Chip** [Submitty/Submitty#9592]
**Describe the bug**
As an instructor, when you go to the Grade Override page, you have the ability to override a grade for a student. Once that happens, a table designed to be a history log, appears to show which student you gave an override to and what is the new grade. However, once you reload the page, that table disappears and when you give another grade override, you can't see the old ones. Furthermore, in that table, there isn't a column for which gradeable the instructor chose for that grade override, so there isn't a way to remember which one they chose.
**Expected behavior**
A new column to record the gradeable selected should be added to the table.
The table shouldn't disappear after reloading in order to show a log of all grade overrides. 
**To Reproduce**
1. Log in as instructor 
2. Go to the page Grade Override
3. Select a Gradeable and a student id
4. Give new score
5. See first error ( no column that shows gradeable )
6. Reload the page and see the second error ( the table disappears)

**Configuration**
 - OS: [e.g. Windows, Linux, ...]

**Screenshots**
![image](https://github.com/Submitty/Submitty/assets/131885371/7c48850e-29d2-452d-b6d3-26867b3cd6c7)

**Additional context**

**Comment by ziesski** [comment]
I reviewed it and the data is stored properly in the database. The problem you are encountering may be confusing because select Gradeable (drop down) is the way to control/pick the gradeable. So if you overrode a grade for "aphacker" in gradeable "Closed Homework", then you would have to select "Closed Homework" from the drop down menu to see the table. 

I agree that it could be misleading, and may need design change, but the functionality is working as expected.
