### ISSUE TITLE
Investigate splitting apart Submitty into separate repositories per component

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#965]
Right now, we have most of the code in one monolithic repo (with analysis tools and samples in other repos). However, while the code serves for one continuous e2e pipeline (submission -> autograder -> grading -> rainbow grades), they don't share a strict linkage and could be tested (and are) independently. 

We should investigate the usage of git submodules/subtrees to allow us to split all pieces apart into their own repos and then have this repo act a container. Each repo would have unit/e2e tests that would test just the components of that repo.

We would then have Travis run tests on this repo regularly as a cron job that pulls from master on all other repos to ensure the pipeline keeps working.

Advantages would be smaller/quicker testing of each component, disadvantage would be more confusing git workflow.

The proposed "subrepos" would be:
1) PHP Website (site/)
2) Autograder code (grading/)
3) Rainbow Grades (RainbowGrades/)
4) Tutorial (already in own repo)
5) AnalysisTools (already in own repo)

Each would have its own internal structure of:
src/
tests/
Vagrantfile (if applicable)
.travis.yml
README.md

and then have their own set of requirements. That means that PHP Website would have a composer.json (instead of having a global one), Autograder and AnalysisTools have make, etc.

**Comment by MasterOdin** [comment]
We could also use [git subrepo](https://github.com/ingydotnet/git-subrepo) which I think is actually the most straight forward of options (with the only downside being that it requires an installation).

However, it still requires some amount of "proper usage" to get used to the updated workflow of things for at least developing. Installing on the live server would be the easiest as it would remain just "git pull" and no one would be the wiser on things. The main difference would be having to do `git subrepo push` on the subrepos when changes are made (if not developing a repository individually).

**Comment by MasterOdin** [comment]
Another option (and I think the best following the discussion today) is [gitman](https://github.com/jacebrowning/gitman) which allows us to leverage Git as our dependency manager for everything. This way, we add a "gitman.yml" file to each repo that has dependencies and they get pulled in automatically. We don't have the concept of "dev dependencies" using this tool, but I think the repeated dependencies isn't that big an issue.

In thinking about this, I think I'd also like to accomplish what was talked about in #481 to deal with "what is the working version" of the various dependencies. So, we have a "master" branch which points to specific tags for each dependency and then "develop" which points to the master branch of all dependencies. The "develop" branch gets built on Travis on a daily build using [Travis-CI Cron](https://docs.travis-ci.com/user/cron-jobs/) with an email notification for any failure from this so as to catch any potential inadvertent breaks.

Setup would be: (each bullet point is a repository and the sub-bullets are dependency)
* Submitty
  * Website (site/)
  * Grading (grading/)
    * AnalysisTools
    * Tutorial
  * rainbow-grades (RainbowGrades/)
  * AnalysisTools
  * Tutorial

**Comment by MasterOdin** [comment]
So investigation of the tools reveals that none of them quite match what we want to do and requires us to write our own (or make a fork of gitman).

The primary usage would be:
1. Clone submitty repository
2. Run tool to get all dependencies
3. Make branch of a dependency and work in it (maybe commit, maybe not)
4. Use tool to update all other dependencies, leaving branched dependency alone (gitman fails here)

Features should be (I'm going to call the tool gitvier)
1. Use tool to get all dependencies (`gitvier install`)
2. Update any non-edited dependency (`gitvier pull [subdirectory...]`)
3. Branch one/all dependencies (`gitvier branch [subdirectory]`)
4. Add/remove over any dependency (`gitvier add *`, `gitvier add subdirectory/*`, etc.)
5. Commit for any dependecy (`gitvier commit -m "message" [subdirectory]`)
6. Push any dependency (`gitvier push [subdirectory]`)

**Comment by prestoncarman** [comment]
Just wanted to throw out an idea from a recent Java based project I worked on. In this project, we use a single repository with many maven projects. The maven projects included a XML file which defines the project (dependencies, tests, etc.). All the project code is stored in a folder and has its own folder structure. While I know this is not java, I wanted to see what you thought about keeping all the code in one repository, but have different folders that were used for each component.

I know from our experience with Submitty, trying to track down issues in the current environment can be a bit difficult due to code being in different repo/projects. Its not clear how code is related because the install script hides some of these details during the install process. One only learns about these projects after looking at the install script code. (This may just be an education / standardization process with the Submitty install.) Just saying it could be nice to have all the issues/code/discussion under one location.

If you kept all the code in a single repository, the script to run all the tests for each component could be more complicated as it has to consider each different code base. The trade off would be having nice repositories with a simple test framework that requires extra knowledge of how the pieces fit together or a single repository with a more complicated test framework to launch component tests. 

Either way, I think good documentation will help with the process. Also, I think the top level (umbrella) project should have system tests that test all the components working together.

**Comment by bmcutler** [comment]
Opened 2 new issues for remaining repos to split out.
