### ISSUE TITLE
Sort point's take away options in grading base on individual parts

### ISSUE THREAD

**Issue by ZheyuDeng** [Submitty/Submitty#9856]
**What problem are you trying to solve with Submitty**
A friend who is mentor of cs1 noticed when gradingk, the format looks like this:
![331515504062133026](https://github.com/Submitty/Submitty/assets/122962727/3420039d-4707-46b1-9658-abcfda58c3de)
Noticed when graders are trying to choose such as part a minor error, for example, they will need to go all the way down and look for part a amoung other parts.

**Describe the way you'd like to solve this problem**
He suggusted it is better to organize every option for part a together on the top follow up by b c d e, so when graders are trying to take partial points away from a specific part, they wouldn't have to spend as much time finding it.

**Comment by williamjallen** [comment]
If I'm understanding your request properly, I believe that this is a problem with the way the course has set up marks, rather than an issue with Submitty.  Submitty already supports the ability to order marks.

In the future, please include a screenshot of the problem with a minimal reproducible example, rather than a picture of someone's screen.

**Comment by bmcutler** [comment]
This is not a Submitty bug or feature request.  This is about the design of the grading rubric.  
The ordering of the rubric items is done by the grading staff. 
Please talk to the instructor or head TA if you suggestions to improve the grading experience.
